SELECT FSPRODUTO.CODPRODUTO, FSPRODUTO.DESCRICAO, FSPRODUTOPARAMESTAB.CODESTAB, FSPRODUTOPARAMESTAB.STATUS,
       CASE
         WHEN (FSPRODUTOPARAMESTAB.STATUS = 0) THEN 'Inativo'
         WHEN (FSPRODUTOPARAMESTAB.STATUS = 1) THEN 'Ativo'
         WHEN (FSPRODUTOPARAMESTAB.STATUS = 2) THEN 'Fora de Linha' 
         WHEN (FSPRODUTOPARAMESTAB.STATUS = 3) THEN 'Novo' 
         WHEN (FSPRODUTOPARAMESTAB.STATUS = 4 ) THEN 'Zerado'        
       END AS DESC_STATUS_CASE,
       DECODE(FSPRODUTOPARAMESTAB.STATUS, 0, 'Inativo',
                                          1, 'Ativo',
                                          2, 'Fora de Linha',
                                          3, 'Novo',
                                          4, 'Zerado') AS DESC_STATUS_DECODE,
       FSPRODUTOPARAMESTAB.CODESTOQUE, FSLOCALESTOQUE.DESCRICAO AS DESC_ESTOQUE
  FROM FSPRODUTO, FSPRODUTOPARAMESTAB, FSLOCALESTOQUE
 WHERE FSPRODUTOPARAMESTAB.CODPRODUTO = FSPRODUTO.CODPRODUTO --join
   AND FSLOCALESTOQUE.CODESTOQUE (+)= FSPRODUTOPARAMESTAB.CODESTOQUE --left join
   AND FSPRODUTOPARAMESTAB.CODESTAB = 1
   AND FSPRODUTOPARAMESTAB.STATUS IN (1, 3)

SELECT FSPRODUTO.CODPRODUTO, FSPRODUTO.DESCRICAO, FSPRODUTOPARAMESTAB.CODESTAB, FSPRODUTOPARAMESTAB.STATUS,
       CASE
         WHEN (FSPRODUTOPARAMESTAB.STATUS = 0) THEN 'Inativo'
         WHEN (FSPRODUTOPARAMESTAB.STATUS = 1) THEN 'Ativo'
         WHEN (FSPRODUTOPARAMESTAB.STATUS = 2) THEN 'Fora de Linha' 
         WHEN (FSPRODUTOPARAMESTAB.STATUS = 3) THEN 'Novo' 
         WHEN (FSPRODUTOPARAMESTAB.STATUS = 4 ) THEN 'Zerado'        
       END AS DESC_STATUS_CASE,
       DECODE(FSPRODUTOPARAMESTAB.STATUS, 0, 'Inativo',
                                          1, 'Ativo',
                                          2, 'Fora de Linha',
                                          3, 'Novo',
                                          4, 'Zerado') AS DESC_STATUS_DECODE,
       FSPRODUTOPARAMESTAB.CODESTOQUE
  FROM FSPRODUTO, FSPRODUTOPARAMESTAB
 WHERE FSPRODUTOPARAMESTAB.CODPRODUTO = FSPRODUTO.CODPRODUTO 
   AND FSPRODUTOPARAMESTAB.CODESTAB = 1
   AND FSPRODUTOPARAMESTAB.STATUS NOT IN (0, 4)
   AND FSPRODUTOPARAMESTAB.CODESTOQUE IN (SELECT FSLOCALESTOQUE.CODESTOQUE
                                            FROM FSLOCALESTOQUE
                                           WHERE FSLOCALESTOQUE.CLASSIFICACAO = 'A')
                                           
 SELECT FSPRODUTO.CODPRODUTO, FSPRODUTO.DESCRICAO, FSPRODUTOPARAMESTAB.CODESTAB, FSPRODUTOPARAMESTAB.STATUS,
       CASE
         WHEN (FSPRODUTOPARAMESTAB.STATUS = 0) THEN 'Inativo'
         WHEN (FSPRODUTOPARAMESTAB.STATUS = 1) THEN 'Ativo'
         WHEN (FSPRODUTOPARAMESTAB.STATUS = 2) THEN 'Fora de Linha' 
         WHEN (FSPRODUTOPARAMESTAB.STATUS = 3) THEN 'Novo' 
         WHEN (FSPRODUTOPARAMESTAB.STATUS = 4 ) THEN 'Zerado'        
       END AS DESC_STATUS_CASE,
       DECODE(FSPRODUTOPARAMESTAB.STATUS, 0, 'Inativo',
                                          1, 'Ativo',
                                          2, 'Fora de Linha',
                                          3, 'Novo',
                                          4, 'Zerado') AS DESC_STATUS_DECODE,
       FSPRODUTOPARAMESTAB.CODESTOQUE, FSLOCALESTOQUE.DESCRICAO AS DESC_ESTOQUE
  FROM FSPRODUTO, FSPRODUTOPARAMESTAB, FSLOCALESTOQUE
 WHERE FSPRODUTOPARAMESTAB.CODPRODUTO = FSPRODUTO.CODPRODUTO 
   AND FSLOCALESTOQUE.CODESTOQUE = FSPRODUTOPARAMESTAB.CODESTOQUE
   AND FSPRODUTOPARAMESTAB.CODESTAB = 1
   AND FSPRODUTOPARAMESTAB.STATUS IN (1, 3)   
   AND EXISTS (SELECT 1
                 FROM FSSALDOESTOQUE
                WHERE FSSALDOESTOQUE.CODPRODUTO = FSPRODUTOPARAMESTAB.CODPRODUTO
                  AND FSSALDOESTOQUE.CODESTAB = FSPRODUTOPARAMESTAB.CODESTAB
                  AND FSSALDOESTOQUE.CODESTOQUE = FSPRODUTOPARAMESTAB.CODESTOQUE
                  AND (FSSALDOESTOQUE.ANTERIOR + FSSALDOESTOQUE.ENTRADA - FSSALDOESTOQUE.SAIDA) > 0)                                     
                  
SELECT *
  FROM FSPRODUTOPARAMESTAB
 WHERE FSPRODUTOPARAMESTAB.CODESTOQUE IS NULL                 
 
SELECT *
  FROM FSPRODUTOPARAMESTAB
 WHERE FSPRODUTOPARAMESTAB.CODESTOQUE IS NOT NULL   
 
SELECT FSPRODUTOPARAMESTAB.CODPRODUTO, NVL(FSPRODUTOPARAMESTAB.CODESTOQUE, 'LOCAL DE ESTOQUE N�O INFORMADO') DESC_ESTOQUE
  FROM FSPRODUTOPARAMESTAB
  
SELECT FSPRODUTOPARAMESTAB.CODPRODUTO, FSPRODUTOPARAMESTAB.CODAPLICENTRADA, FSPRODUTOPARAMESTAB.CODAPLICSAIDA, 
       NVL(NVL(TO_CHAR(FSPRODUTOPARAMESTAB.CODAPLICENTRADA), TO_CHAR(FSPRODUTOPARAMESTAB.CODAPLICSAIDA)), 'SEM APLICACAO') APLICACAO
  FROM FSPRODUTOPARAMESTAB
 WHERE FSPRODUTOPARAMESTAB.CODESTAB = 1
 
SELECT SYSDATE 
  FROM DUAL
  
SELECT TO_DATE('20/10-1970 13:52', 'DD/MM-YYYY HH24:MI')
  FROM DUAL
  
SELECT TO_CHAR(SYSDATE, 'HH24:MI:SS')
  FROM DUAL