
--Inserir dados nas tabelas um a um
INSERT INTO NOME_DA_TABELA VALUES(VALUE1,'VALUE4','VALUE3','VALUE4');
INSERT INTO NOME_DA_TABELA VALUES(VALUE1,'VALUE4','VALUE3','VALUE4');
INSERT INTO NOME_DA_TABELA VALUES(VALUE1,'VALUE4','VALUE3','VALUE4');

--Inserir dados nas tabelas multiplos
INSERT ALL
  INTO NOME_DA_TABELA VALUES (VALUE1,'VALUE4','VALUE3','VALUE4')
  INTO NOME_DA_TABELA VALUES (VALUE1,'VALUE4','VALUE3','VALUE4')
  INTO NOME_DA_TABELA VALUES (VALUE1,'VALUE4','VALUE3','VALUE4')
SELECT * FROM DUAL;