
--FUNCTIONS SINGLE ROW

--Arredonda número
SELECT ROUND(NUMERO_A_SER_ARREDONDADO, QUANTIDADE_DE_CASAS_DECIMAIS)
  FROM DUAL;

--Corta as casas decimais sem arredondar
SELECT TRUNC(NUMERO_A_SER_ARREDONDADO,QUANTIDADE_DE_CASAS_DECIMAIS)
  FROM DUAL;

--Retorna o resto da divisão
SELECT MOD(DIVIDENDO,DIVISOR)
  FROM DUAL;

-- ARREDONDA SEMPRE PARA CIMA (RETORNANDO INTEIRO) 
SELECT CEIL(15.123456789)
  FROM DUAL

-- ARREDONDA SEMPRE PARA BAIXO (RETORNANDO INTEIRO)
SELECT FLOOR(15.987654321) 
  FROM DUAL      

--FUNCTIONS MULTI ROWS

--Contador de registros
SELECT COUNT(*) as QUANTIDADE_DE_REGISTROS
 FROM NOME_DA_TABELA;

--Contador de registros tirando nulos
SELECT COUNT(NOME_DA_COLUNA)
  FROM NOME_DA_TABELA;

--Média da coluna total
SELECT AVG(NOME_DA_COLUNA) AS MEDIA
  FROM NOME_DA_TABELA;

--Retorna maior valor da coluna
SELECT MAX(NOME_DA_COLUNA)
  FROM NOME_DA_TABELA;

--Retorna menor valor da coluna
SELECT MIN(NOME_DA_COLUNA)
  FROM NOME_DA_TABELA;

--Soma da coluna
SELECT SUM(NOME_DA_COLUNA)
  FROM NOME_DA_TABELA;







 
