--Arredonda número
SELECT ROUND(NUMERO_A_SER_ARREDONDADO, QUANTIDADE_DE_CASAS_DECIMAIS)
  FROM DUAL;

--Corta as casas decimais sem arredondar
SELECT TRUNC(NUMERO_A_SER_ARREDONDADO,QUANTIDADE_DE_CASAS_DECIMAIS)
  FROM DUAL;

--Retorna o resto da divisão
SELECT MOD(DIVIDENDO,DIVISOR)
  FROM DUAL;
 
