
SELECT *
  FROM FSPRODUTOPARAMESTAB;
  
SELECT * 
  FROM VEPEDVENDA;
  
SELECT *
  FROM VEITEMPEDIDO;
  
--SUM OVER PARTITION BY CODPRODUTO E CODESTAB
SELECT DISTINCT VEITEMPEDIDO.VALORUNITARIO, VEPEDVENDA.CODESTAB, VEITEMPEDIDO.CODPRODUTO,
                SUM(VEITEMPEDIDO.VALORUNITARIO) OVER (PARTITION BY VEITEMPEDIDO.CODPRODUTO,VEPEDVENDA.CODESTAB ORDER BY VEPEDVENDA.CODESTAB ) VALOR_ACUMULADO_CODEMPRESA_TIPOPRODUTO
  FROM VEPEDVENDA,VEITEMPEDIDO
 WHERE VEPEDVENDA.CODESTAB = VEITEMPEDIDO.CODESTAB
 AND VEPEDVENDA.CODPEDVENDA = VEITEMPEDIDO.CODPEDVENDA;
  
--SUM OVER PARTITION BY DATAAPROV
SELECT VEITEMPEDIDO.VALORUNITARIO,VEPEDVENDA.CODESTAB, VEITEMPEDIDO.CODPRODUTO, VEPEDVENDA.DATAAPROV,
       SUM(VEITEMPEDIDO.VALORUNITARIO) OVER (PARTITION BY VEPEDVENDA.DATAAPROV ORDER BY VEPEDVENDA.CODESTAB) VALOR_ACUMULADO_DATAAPROV
  FROM VEPEDVENDA,VEITEMPEDIDO
 WHERE VEPEDVENDA.CODESTAB = VEITEMPEDIDO.CODESTAB
 AND VEPEDVENDA.CODPEDVENDA = VEITEMPEDIDO.CODPEDVENDA; 
 
--LEAD COM CODNATOPER
SELECT  VEITEMPEDIDO.CODNATOPER,VEITEMPEDIDO.VALORUNITARIO, LEAD(VEITEMPEDIDO.VALORUNITARIO) OVER (ORDER BY VEITEMPEDIDO.CODNATOPER) PROXIMO_VALOR
  FROM VEITEMPEDIDO;
 
 
--LAG COM DESCONTO
SELECT  VEITEMPEDIDO.CODNATOPER,VEITEMPEDIDO.VALORUNITARIO, LAG(VEITEMPEDIDO.VALORUNITARIO) OVER (ORDER BY VEITEMPEDIDO.DESCONTO) VALOR_ANTERIOR
  FROM VEITEMPEDIDO;

 
--GROUP BY ROLLUP COM 1 COLUNA
SELECT CODESTAB AS "Código do Estabelecimento", SUM(ROUND(VALORUNITARIO)) AS "TOTAL D POR ESTABELECIMENTO"
  FROM VEITEMPEDIDO
 GROUP BY ROLLUP(CODESTAB);
 
--GROUP BY ROLLUP COM + DE 1 COLUNA
SELECT CODESTAB,CODNATOPER,SUM(ROUND(VALORUNITARIO))
  FROM VEITEMPEDIDO
 WHERE CODNATOPER = 52
 GROUP BY ROLLUP (CODNATOPER, CODESTAB);
 
 --GROUP BY ROLLUP COM + DE 1 COLUNA FORMATADO
SELECT CODESTAB,CODNATOPER,SUM(ROUND(VALORUNITARIO))
  FROM VEITEMPEDIDO
 WHERE CODNATOPER = 52
 GROUP BY ROLLUP (CODNATOPER, CODESTAB);
 
 
--GROUP BY ROLLUP COM + DE 1 COLUNA E COM + DE 1 TABELA
SELECT FSPRODUTOPARAMESTAB.CODTIPO, VEITEMPEDIDO.CODNATOPER, SUM(ROUND(VEITEMPEDIDO.VALORUNITARIO))
  FROM VEITEMPEDIDO,FSPRODUTOPARAMESTAB
 WHERE CODNATOPER = 52
 AND FSPRODUTOPARAMESTAB.CODESTAB = VEITEMPEDIDO.CODESTAB
 AND FSPRODUTOPARAMESTAB.CODPRODUTO = VEITEMPEDIDO.CODPRODUTO
 GROUP BY ROLLUP (VEITEMPEDIDO.CODNATOPER, FSPRODUTOPARAMESTAB.CODTIPO);
 

 

 
 