TABELAS: VEPEDVENDA,FSPRODUTOPARAMESTAB,VEITEMPEDIDO

SUM PARTITION BY POR CODESTAB(VEITEMPEDIDO.CODESTAB) E TIPO DE PRODUTO(VEITEMPEDIDO.CODPRODUTO)

SUM ORDER POR DATA DE APROVAÇÃO DE PEDIDO (VEPEDVENDA.DATAAPROV)

LEAD COM COD NATUREZA DE OPERAÇÃO (VEITEMPEDIDO.CODNATOPER)

LAG COM DESCONTO (VEITEMPEDIDO.DESCONTO)

GROUP BY ROLLUP COM CODESTAB(VEITEMPEDIDO.CODESTAB), NATUREZA DE OPERAÇÃO(VEITEMPEDIDO.CODNATOPER) 
E TIPO DE PRODUTO (VEITEMPEDIDO.CODPRODUTO)

VEPEDVENDA PAI DE VEITEMPEDIDO
FSPRODUTOPARAMESTAB
