
--Entre dois intervalos númericos
SELECT NOME_DA_COLUNA
  FROM NOME_DA_TABELA
  WHERE NOME_DA_COLUNA BETWEEN 10 AND 20;

--Entre dois intervalos de data
SELECT NOME_DA_COLUNA
  FROM NOME_DA_TABELA
  WHERE NOME_DA_COLUNA BETWEEN TO_DATE('25/08/2010 22:00','DD/MM/YYYY HH24:MI') AND TO_DATE('25/08/2010 23:26','DD/MM/YYYY HH24:MI');

--Múltiplos valores
SELECT NOME_DA_COLUNA
  FROM NOME_DA_TABELA
 WHERE NOME_DA_COLUNA IN (1,2,3,4,5,6);

--Menos estes mltiplos valores
SELECT NOME_DA_COLUNA
  FROM NOME_DA_TABELA
 WHERE NOME_DA_COLUNA NOT IN (1,2,3,4,5,6);

--Valores nulos
SELECT NOME_DA_COLUNA
  FROM NOME_DA_TABELA
 WHERE NOME_DA_COLUNA IS NULL;

--Exceto valores nulos
SELECT NOME_DA_COLUNA
  FROM NOME_DA_TABELA
 WHERE NOME_DA_COLUNA IS NOT NULL;

 --String igual a valor especificado
SELECT NOME_DA_COLUNA
  FROM NOME_DA_TABELA
 WHERE NOME_DA_COLUNA LIKE '%JAVA%'