--RANK() OVER ORDER BY POR SOMA_TOTAL AGRUPADA POR COD_ALUNO COM POSIÇÕES EMPATADAS
SELECT COD_ALUNO,
       SUM(TOTAL) SOMA_TOTAL,
       RANK() OVER (ORDER BY SUM(TOTAL) DESC) POSICAO
  FROM TCONTRATO2
 GROUP BY (COD_ALUNO);


--DENSE_RANK() OVER (POSIÇÕES EMPATADAS, PORÉM APÓS AS POSIÇÕES EMPATADAS O NÚMERO SEGUE A SEQUENCIA SER PULAR OS QUE ESTÃO EMPATADOS)
SELECT COD_ALUNO,
       TOTAL,
       RANK() OVER (ORDER BY TOTAL DESC) "RANK()",
       DENSE_RANK() OVER (ORDER BY TOTAL DESC) "DENSE_RANK()"       
  FROM TCONTRATO2
 GROUP BY (COD_ALUNO,TOTAL);  

--RATIO_TO_REPORT() (% DE CADA ITEM EM RELAÇÃO AO TOTAL)
SELECT Cod_aluno,
       SUM(TOTAL) "Total do cliente",   
       ROUND (RATIO_TO_REPORT(SUM(TOTAL)) OVER () *100,2)"% do Total"
  FROM TCONTRATO2
 GROUP BY (COD_ALUNO);

--RANK() OVER PARTITION BY (POSIÇÃO POR GRUPO)
SELECT DATA,
       COD_ALUNO,
       SUM(TOTAL),
       RANK () OVER (PARTITION BY DATA ORDER BY SUM(TOTAL) DESC) POSICAO
  FROM TCONTRATO2
 GROUP BY (DATA, COD_ALUNO)
 ORDER BY DATA;


/*Exeplos em:
C:\Users\Hino\Documents\Treinamento SQL - Oracle\Material\Treinamento Hino\Will\EX1
C:\Users\Hino\Documents\Treinamento SQL - Oracle\Projetos\Projeto 2 - Material Udemy\Editor\Comandos PL-SQL\CAP25_GROUP_BY
C:\Users\Hino\Documents\Treinamento SQL - Oracle\Projetos\Projeto 2 - Material Udemy\Editor\Comandos PL-SQL\CAP25_PART2_FUNCANALIT
*/