--group by é usando quando foi usado função de grupo e um dos registros não são incluidos nas funções
SELECT column_name(s)
  FROM table_name
 WHERE condition
 GROUP BY column_name(s)
 ORDER BY column_name(s);

Exemplo udemy:
SELECT COD_ALUNO,
       COUNT(*) AS QTDE_CONTRATO,
       Sum(TOTAL) AS VALOR_TOTAL
  FROM TCONTRATO2
 GROUP BY COD_ALUNO;


--HAVING FUNCIONA COMO A CLAUSULA WHERE, PÓREM PARA FUNÇÕES DE GRUPO
SELECT column_name(s)
  FROM table_name
 WHERE condition
 GROUP BY column_name(s)
 HAVING condition função de grupo
 ORDER BY column_name(s);

--EXEMPLO UDEMY:
SELECT COD_ALUNO, AVG(TOTAL) MEDIA
FROM TCONTRATO2
WHERE COD_ALUNO > 0
HAVING AVG(Total) > 500
GROUP BY COD_ALUNO
ORDER BY COD_ALUNO;

--COMANDOS AVANÇADOS:

--GROUP BY ROLLUP (AGRUPA PELAS COLUNAS INDICADAS, FORNECENDO UM SUBTOTAL E UM TOTAL)
SELECT COD_ALUNO,
       CASE
         WHEN DATA IS NULL AND COD_ALUNO IS NOT NULL
            THEN 'Sub-total'
         WHEN COD_ALUNO IS NULL
            THEN 'Total'
         ELSE 
            TO_CHAR(DATA) 
        END DESCRICAO,
        ROUND(AVG(DESCONTO),2) MEDIA_DESCONTO,
        SUM(TOTAL) SOMA_TOTAL
  FROM TCONTRATO2
 GROUP BY ROLLUP(COD_ALUNO, DATA);
 --ESTRUTURA: PRIMEIRO REGISTROS AGRUPADOS POR COD_ALUNO, DEPOIS SUB-TOTAL DESSES REGISTROS, OUTROS REGISTROS AGRUPADOS POR COD_ALUNO, DEPOIS SUB-TOTAL DESSES REGISTROS, TOTAL GERAL.


--GROUP BY CUBE
 SELECT COD_ALUNO,
        DATA,
        SUM(TOTAL)
  FROM TCONTRATO2
 GROUP BY CUBE (COD_ALUNO, DATA);     
--ESTRUTURA: PRIMEIRO TOTAL GERAL, DEPOIS SUB-TOTAIS POR DATA, DEPOIS SUB-TOTAIS POR COD_ALUNO, DEPOIS OS REGISTROS DO SUBTOTAL ANTERIOR


--GROUP BY GROUPING (RETORNA 0 EM SUBTOTAIS E 1 EM TOTAL)
SELECT GROUPING(COD_ALUNO), 
       CASE
          WHEN GROUPING(COD_ALUNO) = 0 THEN TO_CHAR(COD_ALUNO)
          ELSE 'Total geral :'
       END AS ALUNO,
       SUM (TOTAL) SOMA_TOTAL
  FROM TCONTRATO2
 GROUP BY ROLLUP(COD_ALUNO);  


--GROUP BY GROUPING_ID
  SELECT DATA,
         GROUPING_ID(DATA) GDT,
         COD_ALUNO,
         GROUPING_ID(COD_ALUNO) GCL,
         CASE
            WHEN GROUPING_ID(COD_ALUNO) = 1 AND GROUPING_ID(DATA) = 0
                THEN 'TOTAL DO DIA'
            WHEN GROUPING_ID(COD_ALUNO) = 1 AND GROUPING_ID(DATA) = 1
                THEN 'TOTAL GERAL'
                
         END AS DESCRICAO,
         SUM(TOTAL) AS SOMA_TOTAL
  FROM TCONTRATO2
  GROUP BY ROLLUP (DATA,COD_ALUNO);    