
--SELECT com inner join
SELECT NC1.NOME_DA_COLUNA, NC2.NOME_DA_COLUNA
  FROM NOME_DA_TABELA_1 AS NC1, NOME_DA_TABELA_2 AS NC2
 WHERE NC1.NOME_DA_COLUNA = NC2.NOME_DA_COLUNA;

--SELECT com Left join
SELECT NC1.NOME_DA_COLUNA, NC2.NOME_DA_COLUNA
  FROM NOME_DA_TABELA_1 AS NC1, NOME_DA_TABELA_2 AS NC2
 WHERE NC1.NOME_DA_COLUNA (+) = NC2.NOME_DA_COLUNA;

 --SELECT com Right join
SELECT NC1.NOME_DA_COLUNA, NC2.NOME_DA_COLUNA
  FROM NOME_DA_TABELA_1 AS NC1, NOME_DA_TABELA_2 AS NC2
 WHERE NC1.NOME_DA_COLUNA = NC2.NOME_DA_COLUNA (+);

--SELECT com Self join

Exemplo udemy:
SELECT Curso.Nome AS Curso,
         Pre_Req.Nome AS Pre_Requisito
  FROM TCURSO2 CURSO, TCURSO2 PRE_REQ
  WHERE CURSO.PRE_REQ = PRE_REQ.COD_CURSO(+)