
CREATE TABLE TALUNO2
(
    COD_ALUNO NUMBER(4) NOT NULL,
    NOME VARCHAR2(30),
    CIDADE VARCHAR2(30),
    CEP VARCHAR2(10),
    PRIMARY KEY (COD_ALUNO)
);

SELECT * FROM TALUNO2;

INSERT ALL
  INTO TALUNO2 (COD_ALUNO,NOME,CIDADE,CEP) VALUES (1,'MARCIO','NOVO HAMBURGO','93000000')
  INTO TALUNO2 (COD_ALUNO,NOME,CIDADE,CEP) VALUES (2,'PAULA','IVOTI','93000000')
  INTO TALUNO2 (COD_ALUNO,NOME,CIDADE,CEP) VALUES (3,'MARIA','SAPIRANGA','93000000') 
SELECT * FROM DUAL;

CREATE TABLE TCURSO2
(  COD_CURSO NUMBER(4) NOT NULL PRIMARY KEY,
   NOME VARCHAR2(30),
   VALOR NUMBER(8,2),
   CARGA_HORARIA NUMBER(4)
);

SELECT * FROM TCURSO2;

INSERT ALL
    INTO TCURSO2 (COD_CURSO,NOME,VALOR,CARGA_HORARIA) VALUES (1,'ORACLE SQL e PL/SQL',500,25)
    INTO TCURSO2 VALUES(2,'ORACLE DBA',499,25)
    INTO TCURSO2 VALUES(3,'JAVA FUNDAMENTOS E OO',1500,100)
    INTO TCURSO2 VALUES(4,'JAVASERVER FACES',1600,100)
    SELECT * FROM DUAL;
    
CREATE TABLE TCONTRATO2
 (
     COD_CONTRATO NUMBER(4) NOT NULL PRIMARY KEY,
     DATA DATE,
     COD_ALUNO NUMBER (4),
     TOTAL NUMBER (8,2),
     DESCONTO NUMBER(5,2)
 );
 
SELECT * 
  FROM TCONTRATO2;
  
INSERT ALL
    INTO TCONTRATO2  VALUES (1, SYSDATE   ,1 ,500,10)
    INTO TCONTRATO2  VALUES (2, SYSDATE   ,2 ,500,10)
    INTO TCONTRATO2  VALUES (3, SYSDATE   ,3 ,1500,05)
    INTO TCONTRATO2  VALUES (4, SYSDATE-5 ,2 ,1600,10)
    INTO TCONTRATO2  VALUES (5, SYSDATE-4 ,5 ,800,10)
    INTO TCONTRATO2  VALUES (6, SYSDATE-3 ,5 ,445,0)
    INTO TCONTRATO2  VALUES (7, SYSDATE-2 ,5 ,445,20)
    SELECT * FROM DUAL;
    
ALTER TABLE TCONTRATO2
 ADD COL_TESTE VARCHAR2(50);

ALTER TABLE TCONTRATO2
 DROP COLUMN COL_TESTE;
 
ALTER TABLE TALUNO2
 RENAME COLUMN NOME TO NOME2;
 
ALTER TABLE TALUNO2
 RENAME COLUMN NOME2 TO NOME;
 
DROP TABLE TABELA;

CREATE SEQUENCE SEQ_ALUNO2 START WITH 4;

INSERT INTO TALUNO2(COD_ALUNO,NOME,CIDADE,CEP)
VALUES (SEQ_ALUNO2.NEXTVAL,'VALDO','CANOAS','11000000');

INSERT INTO TALUNO2(COD_ALUNO,NOME,CIDADE,CEP)
VALUES (SEQ_ALUNO2.NEXTVAL,'ANDRE','IVOTI','12000000');

SELECT * 
  FROM TALUNO2;

DELETE TALUNO2
 WHERE COD_ALUNO > 23;
 
DROP SEQUENCE SEQ_ALUNO2;

SELECT SEQ_ALUNO2.NEXTVAL FROM DUAL;


COMMIT;

CREATE TABLE TITEM2
 ( COD_ITEM NUMBER NOT NULL PRIMARY KEY,
   COD_CURSO NUMBER,
   COD_CONTRATO NUMBER,
   VALOR NUMBER(8,2) );
   
SELECT *
 FROM TITEM2;   
 
 INSERT INTO TITEM2 VALUES (1, 1, 1, 500);
 
 INSERT INTO TITEM2 VALUES (2, 1, 2, 500);

 INSERT INTO TITEM2 VALUES (3, 3, 3, 1500);
 
 INSERT INTO TITEM2 VALUES (4, 4, 4, 1600);
 
 INSERT INTO TITEM2 VALUES (5, 1, 5, 500);
 
 INSERT INTO TITEM2 VALUES (6, 1, 6, 500);
 
 INSERT INTO TITEM2 VALUES (7, 2, 6, 500);
 
 INSERT INTO TITEM2 VALUES (8, 3, 7, 500);
 
 UPDATE TCONTRATO2
    SET DESCONTO = 18
   WHERE COD_CONTRATO = 2;
   
 UPDATE TCONTRATO2
    SET DESCONTO = 20,
        DATA = '05/06/2013',
        TOTAL = 750
   WHERE COD_CONTRATO = 2;
   
 SELECT *
   FROM TCONTRATO2
  WHERE COD_CONTRATO = 2;
  
SELECT *
   FROM TALUNO2;
  
UPDATE TALUNO2
    SET CIDADE = 'LIMEIRA'
  WHERE UPPER(CIDADE) = 'IVOTI';

UPDATE TALUNO2
    SET NOME = 'JEAN'
   WHERE COD_ALUNO = 2;
   
SELECT *
 FROM TCURSO2;
 
 UPDATE TCURSO2
    SET VALOR = 99.99
  WHERE COD_CURSO = 1; 
 