<<<<<<< HEAD:Projetos/Projeto 2 - Material Udemy/Editor/Secao_01.sql
CREATE TABLE TALUNO
=======

CREATE TABLE TALUNO2
>>>>>>> 2b2eb9215040f9719ee79ebe3273494175e85238:Projetos/Projeto 2 - Material Udemy/Editor/Comandos SQL/CAP1_CREATE_INSERT.sql
(
    COD_ALUNO NUMBER(4) NOT NULL,
    NOME VARCHAR2(30),
    CIDADE VARCHAR2(30),
    CEP VARCHAR2(10),
    PRIMARY KEY (COD_ALUNO)
);

SELECT * FROM TALUNO;

INSERT ALL
  INTO TALUNO (COD_ALUNO,NOME,CIDADE,CEP) VALUES (1,'MARCIO','NOVO HAMBURGO','93000000')
  INTO TALUNO (COD_ALUNO,NOME,CIDADE,CEP) VALUES (2,'PAULA','IVOTI','93000000')
  INTO TALUNO (COD_ALUNO,NOME,CIDADE,CEP) VALUES (3,'MARIA','SAPIRANGA','93000000') 
SELECT * FROM DUAL;

CREATE TABLE TCURSO
(  COD_CURSO NUMBER(4) NOT NULL PRIMARY KEY,
   NOME VARCHAR2(30),
   VALOR NUMBER(8,2),
   CARGA_HORARIA NUMBER(4)
);

SELECT * FROM TCURSO;

INSERT ALL
    INTO TCURSO (COD_CURSO,NOME,VALOR,CARGA_HORARIA) VALUES (1,'ORACLE SQL e PL/SQL',500,25)
    INTO TCURSO VALUES(2,'ORACLE DBA',499,25)
    INTO TCURSO VALUES(3,'JAVA FUNDAMENTOS E OO',1500,100)
    INTO TCURSO VALUES(4,'JAVASERVER FACES',1600,100)
    SELECT * FROM DUAL;
    
CREATE TABLE TCONTRATO
 (
     COD_CONTRATO NUMBER(4) NOT NULL PRIMARY KEY,
     DATA DATE,
     COD_ALUNO NUMBER (4),
     TOTAL NUMBER (8,2),
     DESCONTO NUMBER(5,2)
 );
 
SELECT * 
  FROM TCONTRATO;
  
INSERT ALL
    INTO TCONTRATO  VALUES (1, SYSDATE   ,1 ,500,10)
    INTO TCONTRATO  VALUES (2, SYSDATE   ,2 ,500,10)
    INTO TCONTRATO  VALUES (3, SYSDATE   ,3 ,1500,05)
    INTO TCONTRATO  VALUES (4, SYSDATE-5 ,2 ,1600,10)
    INTO TCONTRATO  VALUES (5, SYSDATE-4 ,5 ,800,10)
    INTO TCONTRATO  VALUES (6, SYSDATE-3 ,5 ,445,0)
    INTO TCONTRATO  VALUES (7, SYSDATE-2 ,5 ,445,20)
    SELECT * FROM DUAL;
    
ALTER TABLE TCONTRATO
 ADD COL_TESTE VARCHAR2(50);

ALTER TABLE TCONTRATO
 DROP COLUMN COL_TESTE;
 
<<<<<<< HEAD:Projetos/Projeto 2 - Material Udemy/Editor/Secao_01.sql
ALTER TABLE TALUNO
=======
ALTER TABLE TALUNO2
 RENAME COLUMN NOME TO NOME2;
 
ALTER TABLE TALUNO2
>>>>>>> 2b2eb9215040f9719ee79ebe3273494175e85238:Projetos/Projeto 2 - Material Udemy/Editor/Comandos SQL/CAP1_CREATE_INSERT.sql
 RENAME COLUMN NOME2 TO NOME;
 
DROP TABLE TABELA;

CREATE SEQUENCE SEQ_ALUNO2 START WITH 4;

INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
VALUES (SEQ_ALUNO2.NEXTVAL,'VALDO','CANOAS','11000000');

INSERT INTO TALUNO(COD_ALUNO,NOME,CIDADE,CEP)
VALUES (SEQ_ALUNO2.NEXTVAL,'ANDRE','IVOTI','12000000');

SELECT * 
  FROM TALUNO;

DELETE TALUNO
 WHERE COD_ALUNO > 23;
 
DROP SEQUENCE SEQ_ALUNO2;

SELECT SEQ_ALUNO2.NEXTVAL FROM DUAL;


COMMIT;

CREATE TABLE TITEM
 ( COD_ITEM NUMBER NOT NULL PRIMARY KEY,
   COD_CURSO NUMBER,
   COD_CONTRATO NUMBER,
   VALOR NUMBER(8,2) );
   
SELECT *
 FROM TITEM;   
 
 INSERT INTO TITEM VALUES (1, 1, 1, 500);
 
 INSERT INTO TITEM VALUES (2, 1, 2, 500);

 INSERT INTO TITEM VALUES (3, 3, 3, 1500);
 
 INSERT INTO TITEM VALUES (4, 4, 4, 1600);
 
 INSERT INTO TITEM VALUES (5, 1, 5, 500);
 
 INSERT INTO TITEM VALUES (6, 1, 6, 500);
 
 INSERT INTO TITEM VALUES (7, 2, 6, 500);
 
 INSERT INTO TITEM VALUES (8, 3, 7, 500);
 
 UPDATE TCONTRATO
    SET DESCONTO = 18
   WHERE COD_CONTRATO = 2;
   
 UPDATE TCONTRATO
    SET DESCONTO = 20,
        DATA = '05/06/2013',
        TOTAL = 750
   WHERE COD_CONTRATO = 2;
   
 SELECT *
   FROM TCONTRATO
  WHERE COD_CONTRATO = 2;
  
SELECT *
   FROM TALUNO;
  
UPDATE TALUNO
    SET CIDADE = 'LIMEIRA'
  WHERE UPPER(CIDADE) = 'IVOTI';

UPDATE TALUNO
    SET NOME = 'JEAN'
   WHERE COD_ALUNO = 2;
   
SELECT *
 FROM TALUNO;
 
 UPDATE TCURSO
    SET VALOR = 99.99
  WHERE COD_CURSO = 1; 
  
 RENAME SEQ_ALUNO2
  TO SEQ_ALUNO;
 

