
SELECT *
  FROM TALUNO2;

CREATE OR REPLACE VIEW V_ALUNO2
AS
   SELECT COD_ALUNO AS CODIGO, SALARIO, NOME AS ALUNO, CIDADE,
          ESTADO
     FROM TALUNO2
     WHERE ESTADO = 'SP';
     
SELECT * FROM V_ALUNO2;     
     
     
CREATE OR REPLACE VIEW V_ALUNOTESTE
AS
    SELECT COD_CONTRATO,DATA, TOTAL, NVL(DESCONTO,0) AS DESCONTO, TOTAL-NVL(DESCONTO,0) AS "VALOR A PAGAR"
      FROM TCONTRATO2
      ORDER BY DATA;
      
SELECT * FROM V_ALUNOTESTE;      


CREATE OR REPLACE VIEW V_CONTRATO_TOP2
AS
    SELECT COD_CONTRATO, DESCONTO
    FROM TCONTRATO2
    WHERE DESCONTO >= 10;
    
SELECT *
  FROM V_CONTRATO_TOP2;

SELECT * FROM TCONTRATO2;

SELECT VIEW_NAME, TEXT
  FROM USER_VIEWS;
  
CREATE OR REPLACE VIEW V_ALUNO3(COD, ALUNO, SAL)
AS
    SELECT COD_ALUNO, NOME, SALARIO
    FROM TALUNO2;
    
SELECT * FROM V_ALUNO3;


CREATE OR REPLACE VIEW V_CONTRATO_COMPLEXO
AS
    SELECT TRUNC(DATA) DATA, MAX(NVL(DESCONTO,0)) MAXIMO, AVG(NVL(DESCONTO,0)) MEDIA, COUNT (*) QTDE
      FROM TCONTRATO2
      GROUP BY TRUNC(DATA); 
      
SELECT * FROM V_CONTRATO_COMPLEXO;      
    

