SELECT COD_CONTRATO, DATA, TOTAL, DESCONTO +10
  FROM TCONTRATO2
 WHERE TOTAL > DESCONTO + 10;

ALTER TABLE TALUNO2
 ADD ESTADO CHAR(2) DEFAULT 'SP';
 
ALTER TABLE TALUNO2
  ADD SALARIO NUMBER(8,2) DEFAULT 620;
 
SELECT *
 FROM TALUNO2;

UPDATE TALUNO2
 SET CIDADE = 'LIMEIRA'
 WHERE CIDADE != 'LIMEIRA';

SELECT *
  FROM TALUNO2
 ORDER BY COD_ALUNO;
 
UPDATE TALUNO2
 SET CIDADE = 'BRASILIA',
     ESTADO = 'GO'
WHERE COD_ALUNO = 1; 

UPDATE TALUNO2
 SET ESTADO = 'RS'
WHERE COD_ALUNO IN (3,4); 

UPDATE TALUNO2
  SET ESTADO = 'RJ'
 WHERE CIDADE = 'RIO DE JANEIRO';

COMMIT;

SELECT * 
  FROM TALUNO2
 WHERE ESTADO <> 'RS'
 AND  SALARIO <= 800
 ORDER BY SALARIO DESC;
 
UPDATE TALUNO2
  SET SALARIO = 752
 WHERE ESTADO = 'SP';

INSERT INTO TALUNO2 (COD_ALUNO, NOME,CIDADE)
VALUES (SEQ_ALUNO2.NEXTVAL,'MARIA','PIRACICABA');

INSERT INTO TALUNO2 (COD_ALUNO, NOME,CIDADE)
VALUES (SEQ_ALUNO2.NEXTVAL,'FERNANDA','JUNDIAI');

INSERT INTO TALUNO2 (COD_ALUNO, NOME,CIDADE)
VALUES (SEQ_ALUNO2.NEXTVAL,'MARCIA','CAMPINAS');

INSERT INTO TALUNO2 (COD_ALUNO, NOME,CIDADE)
VALUES (SEQ_ALUNO2.NEXTVAL,'ALDO','COSMOPOLIS');

CREATE SEQUENCE SEQ_ALUNO2
START WITH 6;

SELECT * 
  FROM TALUNO2
 ORDER BY COD_ALUNO;
 
DELETE TALUNO2
 WHERE COD_ALUNO > 20;

UPDATE TALUNO2 SET
ESTADO = 'SP',
SALARIO = 900,
NOME = 'PEDRO'
WHERE COD_ALUNO = 9;




SELECT ESTADO, SALARIO, NOME 
  FROM TALUNO2
 ORDER BY ESTADO, SALARIO DESC;

ALTER TABLE TALUNO2 ADD NASCIMENTO DATE DEFAULT SYSDATE - 1000;

SELECT SYSDATE - SYSDATE - 10 FROM DUAL;

SELECT * FROM TALUNO2;

UPDATE TALUNO2 SET
NASCIMENTO='29/12/1958'
WHERE COD_ALUNO = 9;

UPDATE TALUNO2 SET
NASCIMENTO='16/04/2004'
WHERE COD_ALUNO=2;

SELECT * 
  FROM TALUNO2
 ORDER BY COD_ALUNO;

SELECT COD_ALUNO, NASCIMENTO, Trunc(NASCIMENTO) AS nascimento, NOME
FROM TALUNO2
WHERE Trunc(NASCIMENTO) = '10/10/2001';

SELECT COD_ALUNO, NASCIMENTO, Trunc(NASCIMENTO), NOME
FROM TALUNO2
WHERE NASCIMENTO
 BETWEEN TO_DATE('25/08/2010 22:00','DD/MM/YYYY HH24:MI')
  AND TO_DATE('25/08/2010 23:26','DD/MM/YYYY HH24:MI');

SELECT COD_CONTRATO, DATA, TOTAL,
       DESCONTO, DESCONTO + 1000 AS CALCULO
FROM TCONTRATO2
WHERE TOTAL <= DESCONTO + 1000;

SELECT * FROM TCONTRATO2;

UPDATE TCONTRATO2 SET
DESCONTO = NULL
WHERE COD_CONTRATO = 2;

SELECT * FROM TCONTRATO2
WHERE DESCONTO IS NULL;

SELECT * FROM TCONTRATO2
WHERE DESCONTO IS NOT NULL;

SELECT * FROM TCONTRATO2
WHERE DESCONTO BETWEEN 0 AND 10;


--Nvl 0> Colunar com valor null
--BETWEEN -> Entre
SELECT COD_CONTRATO, TOTAL, DESCONTO, NVL(DESCONTO,0)
FROM TCONTRATO2
WHERE NVL(DESCONTO,0) BETWEEN 0 AND 10;

--mesmo efeito do between

SELECT * FROM TCONTRATO2
WHERE DESCONTO >= 0
AND DESCONTO <= 10
OR DESCONTO IS NULL;

--  IN  /// NOT IN
SELECT * FROM TITEM
WHERE COD_CURSO IN (1, 2, 4);

SELECT * FROM TITEM
WHERE COD_CURSO NOT IN (1, 2, 4);

SELECT * FROM TCURSO2

INSERT INTO TCURSO2 VALUES (5, 'WINDOWS', 1000, 50 );

--CURSOS NAO VENDIDOS
SELECT * FROM TCURSO2
WHERE COD_CURSO NOT IN (SELECT COD_CURSO FROM TITEM)


--CURSOS VENDIDOS
SELECT * FROM TCURSO2
WHERE COD_CURSO IN (SELECT COD_CURSO FROM TITEM)


--equivalente ao SELECT IN
SELECT * FROM TITEM
WHERE COD_CURSO = 1
OR COD_CURSO    = 2
OR COD_CURSO    = 4;

--somente onde a segunda letra seja A
SELECT * FROM TCURSO2 WHERE NOME LIKE 'W%' ;    

SELECT * FROM TCURSO2 WHERE NOME LIKE '%JAVA%';

SELECT * FROM TCURSO2 WHERE NOME LIKE '%FACES';

SELECT * FROM TCURSO2;

COMMIT;

ALTER TABLE TCURSO2 ADD PRE_REQ INTEGER;

UPDATE TCURSO2 SET
PRE_REQ = 1
WHERE COD_CURSO = 2;

UPDATE TCURSO2 SET
PRE_REQ = 3
WHERE COD_CURSO = 4;

--cursos sem pre requisito
SELECT * FROM TCURSO2 WHERE PRE_REQ IS NULL;

--cursos com pre-requisitos
SELECT * FROM TCURSO2 WHERE PRE_REQ IS NOT NULL;

--Precedencia de operadores
-- ()
-- AND
-- OR

SELECT * FROM TCURSO2
WHERE valor > 750
OR valor < 1000
AND carga_horaria = 25;


SELECT * FROM TCURSO2
WHERE (valor > 750
or valor < 1000)
and carga_horaria = 25;


-- Ordem de execução
-- 1 - Paranteses
-- 2 - AND
-- 3 - OR
