CREATE TABLE TDESCONTO2
( CLASSE VARCHAR(2),
  INFERIOR INTEGER,
  SUPERIOR INTEGER );

SELECT * 
  FROM TDESCONTO2
 ORDER BY CLASSE;
 
INSERT INTO TDESCONTO2(CLASSE, INFERIOR, SUPERIOR)
VALUES ('&cla', &inf, &sup);

SELECT * FROM TDESCONTO2
WHERE CLASSE = '&cla';

UPDATE TDESCONTO2 SET
INFERIOR = &inf ,
SUPERIOR = &sup
WHERE CLASSE = '&cla';

DELETE FROM TDESCONTO2
WHERE CLASSE = '&cla';

----------------------------------------
CREATE TABLE TDESCONTO3
  AS SELECT * FROM TDESCONTO2;

DROP TABLE TDESCONTO3;

SELECT * FROM TDESCONTO3;

--Transação (Commit/Rollback)
COMMIT;

--
DELETE FROM TDESCONTO3;

--Deleta todos os registros
ROLLBACK;

--Delete todos os registros da tabela
--Nao tem clausula Where

TRUNCATE TABLE TDESCONTO3;

--Deleta todos os registros nao tem volta/
--nao funciona (Commit/Rollback)


SELECT * FROM TDESCONTO3;

ROLLBACK;

COMMIT;

SELECT * FROM TDESCONTO2;

--Savepoint
SAVEPOINT upd_b;

UPDATE TDESCONTO2 SET
SUPERIOR = 88
WHERE CLASSE = 'B';

SAVEPOINT upd_a;

UPDATE TDESCONTO2 SET
SUPERIOR = 99
WHERE CLASSE = 'A';

--ponto de restauraçao
SAVEPOINT ins_Ok;

INSERT INTO TDESCONTO2(classe, inferior, superior)
VALUES ('&cla', &inf, &sup);

SELECT * 
  FROM TDESCONTO2
  ORDER BY CLASSE;

ROLLBACK TO SAVEPOINT ins_Ok;

ROLLBACK TO SAVEPOINT upd_a;

ROLLBACK TO SAVEPOINT upd_b;

--excluir tabela
DROP TABLE TDESCONTO3;