--COMMANDS DDL

ALTER TABLE TESTE_SALARIOS
 ADD SALARIO NUMBER(7,2);

RENAME TESTE_SETORES TO TESTE_DEPARTAMENTOS;

ALTER TABLE TESTE_FUNCIONARIOS
  RENAME COLUMN IDSETOR TO IDDEPARTAMENTO;
  
ALTER TABLE TESTE_DEPARTAMENTOS
  RENAME COLUMN IDSETOR TO IDDEPARTAMENTO;

ALTER TABLE TESTE_DEPARTAMENTOS
  RENAME COLUMN NOMESETOR TO NOMEDEPARTAMENTO;
  
ALTER TABLE TESTE_DEPARTAMENTOS
  MODIFY (IDGERENTE NULL);






--COMMANDS DDL

-- TABELA SALARIOS
UPDATE TESTE_SALARIOS
 SET SALARIO = 8000
 WHERE NIVEISSAL = 'A';
 
TRUNCATE TABLE TESTE_SALARIOS;

 INSERT ALL
  INTO TESTE_SALARIOS (NIVEISSAL, SALARIO) VALUES ('A',8000)
  INTO TESTE_SALARIOS (NIVEISSAL, SALARIO) VALUES ('B',6000)
  INTO TESTE_SALARIOS (NIVEISSAL, SALARIO) VALUES ('C',4000)
  INTO TESTE_SALARIOS (NIVEISSAL, SALARIO) VALUES ('D',2000)
SELECT * FROM DUAL;

ALTER TABLE TESTE_SALARIOS DROP COLUMN SALARIO;

--TABELA DEPARTAMENTOS
  INSERT ALL
  INTO TESTE_DEPARTAMENTOS (IDSETOR, NOMESETOR, IDGERENTE) VALUES (1,'FINANCEIRO',1)
  INTO TESTE_DEPARTAMENTOS (IDSETOR, NOMESETOR, IDGERENTE) VALUES (2,'COMERCIAL',2)
  INTO TESTE_DEPARTAMENTOS (IDSETOR, NOMESETOR, IDGERENTE) VALUES (3,'ADMINISTRAÇÃO',3)
  INTO TESTE_DEPARTAMENTOS (IDSETOR, NOMESETOR, IDGERENTE) VALUES (4,'DESENVOLVIMENTO',4)
  INTO TESTE_DEPARTAMENTOS (IDSETOR, NOMESETOR, IDGERENTE) VALUES (5,'RECURSOS_HUMANOS',5)
SELECT * FROM DUAL;

--TABELA FUNCIONARIOS
 TRUNCATE TABLE TESTE_FUNCIONARIOS;
 
   INSERT ALL
  INTO TESTE_FUNCIONARIOS (IDFUNC, NOMEFUNC, TELFUNC, EMAILFUNC, IDSETOR, NIVEISSAL) VALUES (1,'Jose',987654321,'josecarlosgamer@gmail.com',1,'B')
  INTO TESTE_FUNCIONARIOS (IDFUNC, NOMEFUNC, TELFUNC, EMAILFUNC, IDSETOR, NIVEISSAL) VALUES (2,'Maria',997557321,'mariavalentina123@hotmail.com',2,'C')
  INTO TESTE_FUNCIONARIOS (IDFUNC, NOMEFUNC, TELFUNC, EMAILFUNC, IDSETOR, NIVEISSAL) VALUES (3,'Claudio',985624481,'claudioaugusto77@outlook.com',4,'A')
  INTO TESTE_FUNCIONARIOS (IDFUNC, NOMEFUNC, TELFUNC, EMAILFUNC, IDSETOR, NIVEISSAL) VALUES (4,'Erick',983453981,'ericksilva8525@yahoo.com',1,'B')
  INTO TESTE_FUNCIONARIOS (IDFUNC, NOMEFUNC, TELFUNC, EMAILFUNC, IDSETOR, NIVEISSAL) VALUES (5,'Fernanda',985614428,'fefe134@gmail.com',3,'A')
SELECT * FROM DUAL;

--SELECTS ALL TABLES

SELECT * 
 FROM TESTE_FUNCIONARIOS;

SELECT * 
 FROM TESTE_SALARIOS
 ORDER BY NIVEISSAL;

SELECT *
 FROM TESTE_DEPARTAMENTOS;



SELECT TESTE_FUNCIONARIOS.IDFUNC,TESTE_FUNCIONARIOS.NOMEFUNC,TESTE_FUNCIONARIOS.TELFUNC,
       TESTE_FUNCIONARIOS.EMAILFUNC,TESTE_FUNCIONARIOS.NIVEISSAL,  
    CASE
        WHEN (TESTE_FUNCIONARIOS.NIVEISSAL = 'A') THEN '8000'
        WHEN (TESTE_FUNCIONARIOS.NIVEISSAL = 'B') THEN '6000'
        WHEN (TESTE_FUNCIONARIOS.NIVEISSAL = 'C') THEN '4000'
        WHEN (TESTE_FUNCIONARIOS.NIVEISSAL = 'D') THEN '2000'
    END AS SALARIOS
 FROM TESTE_FUNCIONARIOS
  ORDER BY NIVEISSAL;
  
  
  
SELECT TF.IDFUNC,TF.NOMEFUNC,TF.TELFUNC,
       TF.EMAILFUNC, TS.SALARIO AS SALARIO
  FROM TESTE_FUNCIONARIOS TF, TESTE_SALARIOS TS
 WHERE TS.NIVEISSAL  = TF.NIVEISSAL
 ORDER BY TS.SALARIO DESC;
 
 
 
SELECT TF.IDFUNC,TF.NOMEFUNC,TF.TELFUNC,TF.EMAILFUNC,
        TS.SALARIO AS SALARIO, TD.NOMEDEPARTAMENTO AS DEPARTAMENTO
  FROM TESTE_FUNCIONARIOS TF, TESTE_SALARIOS TS, TESTE_DEPARTAMENTOS TD
 WHERE TS.NIVEISSAL  = TF.NIVEISSAL 
 AND TD.IDDEPARTAMENTO = TF.IDDEPARTAMENTO;

 
 