 INSERT INTO TESTE_FUNCIONARIOS VALUES (1,'Claudio',19987452289,'claudoaugusto1234@gmail.com',5,'A');
 
 INSERT INTO TESTE_SALARIOS (NIVEISSAL, SALARIO) 
 VALUES ('B',8000);
 
 INSERT INTO TESTE_SALARIOS (NIVEISSAL, SALARIO)
 VALUES ('C',6000);
 
  INSERT INTO TABELA_TESTE_SALARIO (NIVEISSAL, SALARIO)
 VALUES ('D',4000);
 
  INSERT INTO TABELA_TESTE_SALARIO (NIVEISSAL, SALARIO)
 VALUES ('E',2000);
 
  ALTER TABLE TABELA_TESTE_SALARIO
 MODIFY ( NIVEISSAL CHAR(10));
 
 ALTER TABLE TABELA_TESTE_SALARIO
 MODIFY ( SALARIO NUMBER(6));
 
SELECT *
 FROM TABELA_TESTE_FUNCIONARIOS;
 
 ALTER TABLE TABELA_TESTE_FUNCIONARIOS
  MODIFY (TELFUNC NUMBER(11));

  
ALTER TABLE TESTE_SALARIO
RENAME TO TESTE_SALARIOS;

 ALTER TABLE TESTE_SALARIOS
 MODIFY(NIVEISSAL VARCHAR2(10));
 
 DROP TABLE TESTE_SALARIOS;
 

 SELECT *
 FROM TESTE_SALARIOS;
 
UPDATE TESTE_SALARIOS
SET SALARIO = 8000
WHERE NIVEISSAL = 'A';
 
INSERT INTO TESTE_SALARIOS (NIVEISSAL, SALARIO) 
 VALUES ('A',8000); 
 
INSERT INTO TESTE_SALARIOS (NIVEISSAL, SALARIO) 
 VALUES ('B',6000);
 
 INSERT INTO TESTE_SALARIOS (NIVEISSAL, SALARIO)
 VALUES ('C',4000);
 
  INSERT INTO TESTE_SALARIOS (NIVEISSAL, SALARIO)
 VALUES ('D',2000);
 
  INSERT INTO TESTE_SALARIOS (NIVEISSAL, SALARIO)
 VALUES ('E',1000);


 ALTER TABLE TABELA_TESTE_SALARIO
 MODIFY(NIVEISSAL VARCHAR2(1));
 
 DROP TABLE TESTE_SALARIOS;
 
 DROP TABLE TESTE_FUNCIONARIOS;
 
 DROP TABLE TESTE_SETORES;
 
 
 INSERT INTO TANIVEISSALBELA_TESTE_SALARIO (NIVEISSAL, SALARIO) VALUES ('A',10000);
  
