
--Inserir coluna na tabela
ALTER TABLE NOME_DA_TABELA 
  ADD NOME_DA_COLUNA VARCHAR(50);

--Excluir coluna da tabela
ALTER TABLE NOME_DA_TABELA 
  DROP COLUMN NOME_DA_COLUNA;

--Alterar nome de coluna
ALTER TABLE NOME_DA_TABELA 
  RENAME COLUMN NOME_DA_COLUNA TO NOVO_NOME_DA_COLUNA;