
--GERAL:
--INCLUIR CONSTRAINTS
ALTER TABLE NOME_DA_TABELA
  ADD CONSTRAINT NOME_CONSTRAINT TIPO_DA_CONSTRAINT (NOME_DA_COLUNA);

--EXCLUIR CONSTRAINTS
ALTER TABLE NOME_DA_TABELA
  DROP CONSTRAINT NOME_CONSTRAINT

--DESABILITANDO/HABILITANDO CONSTRAINT
ALTER TABLE NOME_DA_TABELA 
  DISABLE CONSTRAINT NOME_CONSTRAINT;

ALTER TABLE NOME_DA_TABELA 
  ENABLE CONSTRAINT NOME_CONSTRAINT;


--PRIMARY KEY:
--PRIMARY KEY COM NOME DEFAULT
CREATE TABLE NOME_DA_TABELA
(
    NOME_DA_COLUNA TIPO PRIMARY KEY
);

--PRIMARY KEY COM NOME DEFINIDO
CREATE TABLE NOME_DA_TABELA
(
    NOME_DA_COLUNA TIPO,
    CONSTRAINT NOME_DA_CONSTRAINT PRIMARY KEY (NOME_DA_COLUNA)
);

--FOREIGN KEY:
--CHAVE ESTRANGEIRA
ALTER TABLE NOME_DA_TABELA 
  ADD CONSTRAINT NOME_DA_CONSTRAINT FOREIGN KEY (NOME_DA_COLUNA) 
  REFERENCES NOME_DA_TABELA_
  
--EXCLUIR CHAVE ESTRANGEIRA
ALTER TABLE NOME_DA_TABELA DROP CONSTRAINT NOME_DA_CONSTRAINT
  CASCADE CONSTRAINT;


--OUTROS TIPOS:
--NOT NULL
CREATE TABLE NOME_DA_TABELA
(
    NOME_DA_COLUNA TIPO NOT NULL
);

--CAMPO ÚNICO
ALTER TABLE NOME_DA_TABELA
  ADD CONSTRAINT NOME_DA_CONSTRAINT UNIQUE (NOME_DA_COLUNA);

--CAMPOS ACEITAM APENAS OS VALORES DEFINIDOS
ALTER TABLE NOME_DA_TABELA
  ADD CONSTRAINT NOME_DA_CONSTRAINT CHECK (NOME_DA_COLUNA IN('VALOR 1','VALOR2'))

ALTER TABLE NOME_DA_TABELA
  ADD CONSTRAINT NOME_DA_CONSTRAINT CHECK (NOME_DA_COLUNA BETWEEN VALOR1 AND VALOR2)



