
--CRIAÇÃO DE TABELA
CREATE TABLE NOME_DA_TABELA
(
  ATRIBUTO1 NUMBER(5) NOT NULL,
  ATRIBUTO2 NUMBER(5,2),
  ATRIBUTO3 CHAR(2),
  ATRIBUTO4 VARCHAR2(10),
  PRIMARY KEY (ATRIBUTO1)
);

--CRIAÇÃO DE TABELA A PARTIR DE OUTRA
CREATE TABLE NOME_DA_NOVA_TABELA
  AS 
    SELECT *
     FROM NOME_DA_TABELA_A_SER_COPIADA

