
--SELECT COM BLOCO ANONIMO COM APENAS 1 REGISTRO DE RETORNO (VARCHAR E NUMBER)
DECLARE
    VVALOR NUMBER (8,2);
    VNOME VARCHAR2(30); 
BEGIN
    SELECT VALOR,  NOME
     INTO VVALOR, VNOME
      FROM TCURSO2
     WHERE COD_CURSO = &COD_CURSO;
     Dbms_Output.Put_Line('VALOR: ' || TO_CHAR(VVALOR,'FM9999.99'));
     Dbms_Output.Put_Line('CURSO: ' || INITCAP(VNOME));
END;


SELECT * 
  FROM TCURSO2
  ORDER BY COD_CURSO;


--SELECT COM BLOCO ANONIMO COM APENAS 1 REGISTRO DE RETORNO (DATA)
DECLARE
    VDT_COMPRA TCONTRATO2.DATA%TYPE;
    VDT_CURSO TCONTRATO2.DATA%TYPE;
BEGIN
    SELECT  DATA    , DATA + 10
      INTO VDT_COMPRA , VDT_CURSO
      FROM TCONTRATO2
     WHERE COD_CONTRATO = &CONTRATO;
     Dbms_Output.Put_Line('DATA DA COMPRA: ' || VDT_COMPRA);
     Dbms_Output.Put_Line('DATA DO CURSO: ' || VDT_CURSO);
END;

SELECT *
  FROM TCONTRATO2;
  
  
SELECT MAX(COD_CONTRATO) FROM TCONTRATO2;

CREATE SEQUENCE SEQ_CONTRATO2 START WITH 8;

DROP SEQUENCE SEQ_CONTRATO1;


-- BLOCO ANONIMO INSERINDO DADOS COM SEQUENCE
DECLARE
    VCOD_CONTRATO TCONTRATO2.COD_CONTRATO%TYPE;
BEGIN
    SELECT SEQ_CONTRATO2.NEXTVAL
    INTO VCOD_CONTRATO
    FROM DUAL;
    
    INSERT INTO TCONTRATO2(COD_CONTRATO, DATA, COD_ALUNO, DESCONTO)
    VALUES (VCOD_CONTRATO, SYSDATE, 2, NULL);
    COMMIT;
    
    Dbms_Output.Put_Line('CRIADO CONTRATO: ' || VCOD_CONTRATO);
END;

SELECT Seq_Contrato2.CURRVAL 
  FROM Dual;
  
SELECT *
  FROM TCONTRATO2
  ORDER BY COD_CONTRATO;
 
DELETE TCONTRATO2
  WHERE COD_CONTRATO > 10;
  
DROP SEQUENCE SEQ_CONTRATO2;

CREATE SEQUENCE SEQ_CONTRATO2 START WITH 11;


--BLOCO ANONIMO COM UPDATE
DECLARE
   VVALOR TCURSO2.VALOR%TYPE := &VALOR;
BEGIN
   UPDATE TCURSO2
     SET VALOR = VALOR+VVALOR
     WHERE CARGA_HORARIA >= 30;
END;

SELECT *
  FROM TCURSO2
  WHERE CARGA_HORARIA >= 30;
 

--INSERT BLOCO ANONIMO SEM COMMIT = NÃO APARECE NO SELECT
BEGIN
   INSERT INTO TALUNO2 VALUES (1001,'ENZO','ARTUR NOGUEIRA','13160-354','SP',3000,'21/09/2004');
END;

--INSERT  BLOCO ANONIMO COM COMMIT = APARECE NO SELECT
BEGIN
   INSERT INTO TALUNO2 VALUES (1002,'ENZO','ARTUR NOGUEIRA','13160-354','SP',3000,'21/09/2004');
   commit;
END;

--INSERT FORA DO BLOCO ANONIMO APARECE NO SELECT
INSERT INTO TALUNO2 VALUES (1003,'ENZO','ARTUR NOGUEIRA','13160-354','SP',3000,'21/09/2004');

SELECT *
  FROM TALUNO2;

DELETE TALUNO2
  WHERE COD_ALUNO > 1000;


--BLOCO ANONIMO COM DELETE
DECLARE
   VCONTRATO TCONTRATO2.COD_CONTRATO%TYPE := &CONTRATO;
BEGIN
   DELETE FROM TCONTRATO2
   WHERE COD_CONTRATO = VCONTRATO;
   COMMIT;
END;

SELECT *
  FROM TCONTRATO2
  ORDER BY COD_CONTRATO;


--ERRO NO_DATA_FOUND

DECLARE
   VDT_COMPRA    TCONTRATO2.DATA%TYPE;
   VTOTAL       TCONTRATO2.TOTAL%TYPE;
   VDT_ATUAL    DATE := SYSDATE;
BEGIN
   SELECT DATA, TOTAL
   INTO   VDT_COMPRA, VTOTAL
   FROM   TCONTRATO2 
   WHERE  DATA = VDT_ATUAL;	
END;


DECLARE
   VCONTRATO NUMBER := &COD_CONTRATO;
   VTEXTO VARCHAR2(50);
BEGIN
   UPDATE TCONTRATO2
    SET DESCONTO = DESCONTO - 2
    WHERE COD_CONTRATO >= VCONTRATO;
    
    --SQL%ROWCOUNT RETORNA A QTDE DE REGISTROS AFETADOS PELO COMANDO SQL
    VTEXTO := SQL%ROWCOUNT;
    
    Dbms_Output.Put_Line(VTEXTO || ' LINHAS ATUALIZADAS.');
    COMMIT;
END;

SELECT *
  FROM TCONTRATO2;