
--IF, ELSE, ELSIF
DECLARE
   VNOME VARCHAR(30) := '&NOME';
   VCIDADE VARCHAR(30);
   VESTADO VARCHAR(2);
BEGIN
   IF (VNOME = 'GAUCHO') THEN
     VCIDADE := 'PORTO ALEGRE';
     VESTADO := 'RS';
   ELSIF (VNOME = 'PAULISTA') THEN
     VCIDADE := 'SÃO PAULO';
     VESTADO := 'SP';
   ELSE
      IF (VESTADO = 'SP') THEN
         VCIDADE := 'PAULISTA';
      ELSE
        VCIDADE := 'OUTROS';
        VESTADO := 'XX';
      END IF;
    END IF;
    Dbms_Output.Put_Line(VCIDADE || ' - ' || VESTADO);
END;

--CASE WHEN
DECLARE
   VESTADO VARCHAR(2) := '&N';
   VNOME VARCHAR (30);
BEGIN
   CASE
     WHEN VESTADO = 'RS' THEN VNOME := 'GAUCHO';
     WHEN VESTADO = 'RJ' OR VESTADO = 'rj' THEN VNOME := 'CARIOCA';
   ELSE
     VNOME := 'OUTROS';
   END CASE;
   Dbms_Output.Put_Line('APELIDO: ' || VNOME);
END;


--ESTRUTURA LOOP
DECLARE
  vContador INTEGER := 0;
BEGIN
  LOOP
    vContador  := VCONTADOR + 1;
    Dbms_Output.Put_Line(vContador);
    EXIT WHEN vContador = 10;
  END LOOP;
  Dbms_Output.Put_Line('Fim do LOOP');
END;


--ESTRUTURA FOR
DECLARE
  VCONTADOR INTEGER;
BEGIN
   FOR VCONTADOR IN 1..10
   LOOP
    Dbms_Output.Put_Line(VCONTADOR);
   END LOOP;
END;

--WHILE LOOP
DECLARE
   VCONTADOR INTEGER := 0;
   VTEXTO VARCHAR (10);
BEGIN
   WHILE VCONTADOR < 10
   LOOP
     VCONTADOR := VCONTADOR + 1;
     IF (VCONTADOR MOD 2)=0 THEN
        VTEXTO := 'PAR';
     ELSE 
        VTEXTO := 'IMPAR';
     END IF;
     Dbms_Output.Put_Line(VCONTADOR || ' -> ' || VTEXTO);
   END LOOP;
END;
