
----  UNION ALL - UNION

SELECT COD_ALUNO, TOTAL, DESCONTO
  FROM TCONTRATO2
 WHERE COD_ALUNO = 1
  UNION ALL       ---Nao agrupa iguais
  --UNION         ---Agrupa iguais
SELECT COD_ALUNO, TOTAL, DESCONTO
  FROM TCONTRATO2
 WHERE TOTAL >= 1000;


-- UNION ALL E UNION - 3 SELECT
SELECT COD_CONTRATO, DATA, TOTAL --, 'UNION 1' AS QUERY
FROM   TCONTRATO2
WHERE  TOTAL >= 1000 AND TOTAL < 2000
--RETURN COD_CONTRATO = 3,4

UNION  ALL

SELECT COD_CONTRATO, DATA, TOTAL -- , 'UNION 2' AS QUERY
FROM   TCONTRATO2
WHERE  DESCONTO IS NOT NULL
--RETURN COD_CONTRATO = 1,2,5,6,7

UNION

SELECT COD_CONTRATO, DATA, TOTAL --, 'UNION 3' AS QUERY
FROM   TCONTRATO2
WHERE  TOTAL > 2000
--RETURN COD_CONTRATO = 1

ORDER  BY COD_CONTRATO;

--ORDER  BY QUERY;




-- INTERSECT (MOSTRA DADOS DUPLICADOS)
SELECT COD_CONTRATO, DATA, DESCONTO, TOTAL
FROM   TCONTRATO2
WHERE  DESCONTO IS NOT NULL

INTERSECT

SELECT COD_CONTRATO, DATA, DESCONTO, TOTAL
FROM   TCONTRATO2
WHERE  TOTAL > 1000

ORDER  BY COD_CONTRATO;


-- MINUS (SELECT1 - SELECT2)
SELECT COD_CONTRATO, DATA, DESCONTO, TOTAL --(1,2,5,6,7)
FROM   TCONTRATO2
WHERE  DESCONTO IS NOT NULL

MINUS  -- traz todos os registros da primeira consulta
       -- menos os da segunda consulta ( ignora repetido )

SELECT COD_CONTRATO, DATA, DESCONTO, TOTAL -- (1)
FROM   TCONTRATO2
WHERE  TOTAL > 2000

ORDER  BY 1;



--Exercicios
--1
SELECT COD_CONTRATO, TOTAL, 'CONTRATOS' STRING
FROM TCONTRATO
 UNION
SELECT COD_CONTRATO, SUM(VALOR) VALOR, 'ITENS' STRING
FROM ITENS
GROUP BY COD_CONTRATO
ORDER BY 3,1;

--2
SELECT COD_CONTRATO, DATA, TOTAL
FROM TCONTRATO
 MINUS
SELECT COD_CONTRATO, DATA, TOTAL
FROM TCONTRATO
WHERE NVL(DESCONTO,0) = 0
 INTERSECT
SELECT CON.COD_CONTRATO, CON.DATA, CON.TOTAL
FROM TALUNO ALU, TCONTRATO CON
WHERE ALU.COD_ALUNO = CON.COD_ALUNO
AND ALU.ESTADO = 'RS';


--TESTE
SELECT COD_ALUNO, TOTAL, DESCONTO -- (1,2,3)
  FROM TCONTRATO2
 WHERE TOTAL >= 1000

  UNION ALL   --(1,3,2,1) MOSTRA TODOS OS DADOS
  --UNION       --(1,2,3) AGRUPA DADOS DUPLICADOS
  --MINUS       -- (2,3) RETIRA DADOS DUPLICADOS
  --INTERSECT   --(1) MOSTRA APENAS OS DADOS DUPLICADOS
SELECT COD_ALUNO, TOTAL, DESCONTO -- (1)
  FROM TCONTRATO2
 WHERE COD_ALUNO = 1;






