INSERT ALL
  INTO TCURSO2 (COD_CURSO,NOME, VALOR)
  INTO TALUNO2 (COD_ALUNO,NOME, SALARIO)
      SELECT COD_CONTRATO+50,'INSERT ALL', 1013
      FROM TCONTRATO2
      WHERE COD_CONTRATO=1;

      --  ALTER TABLE TALUNO2 ADD SALARIO NUMERIC;

SELECT * FROM TCURSO2 ORDER BY COD_CURSO;

SELECT * FROM TALUNO2 ORDER BY COD_ALUNO;

-----**************


CREATE SEQUENCE SEQ_CURSO2 START WITH 100;

--
INSERT ALL
   WHEN TOTAL>=1000  THEN
        INTO TCURSO2 (COD_CURSO, NOME, VALOR)
        VALUES (SEQ_CURSO2.NEXTVAL, 'CURSO>1000', TOTAL)
   WHEN DESCONTO IS NULL THEN
        INTO TCURSO2 (COD_CURSO, NOME, VALOR)
        VALUES (SEQ_CURSO2.NEXTVAL, 'DESCONTO IS NULL', TOTAL)
   SELECT COD_CONTRATO, TOTAL, DESCONTO
   FROM TCONTRATO2 WHERE COD_CONTRATO = 1;


SELECT * FROM TCURSO2;


--Merge
CREATE SEQUENCE SEQ_CON2 START WITH 500;

MERGE INTO TCONTRATO2 TCN
    USING (SELECT COD_ALUNO AS ALUNO
           FROM   TALUNO2
           WHERE  ESTADO = 'RS')
    ON    (TCN.COD_ALUNO = ALUNO)
       WHEN MATCHED THEN --Encontrou o registro
            UPDATE SET DESCONTO = 22
       WHEN NOT MATCHED THEN --nao encontrou o registro
            INSERT(TCN.COD_CONTRATO, TCN.DATA, TCN.COD_ALUNO,
                   TCN.DESCONTO, TCN.TOTAL)
           VALUES( SEQ_CON2.NEXTVAL, SYSDATE, ALUNO, 0, 666);

SELECT * FROM TCONTRATO2

--ALTER TABLE TALUNO2 ADD ESTADO VARCHAR(2) DEFAULT  'RS';

    