
CREATE OR REPLACE FUNCTION CONSULTA_PRECO (PCOD_CURSO NUMBER) RETURN NUMBER
AS
  VVALOR NUMBER;
BEGIN
    SELECT VALOR 
      INTO VVALOR 
      FROM TCURSO2
     WHERE COD_CURSO = PCOD_CURSO;
    
    RETURN (VVALOR);
END; 


DECLARE
   VCOD NUMBER := &CODIGO;
   VVALOR  NUMBER;
   VNOME VARCHAR (30);
BEGIN
    SELECT NOME
      INTO VNOME 
      FROM TCURSO2
     WHERE COD_CURSO = VCOD;
    
    VVALOR := CONSULTA_PRECO(VCOD);
    Dbms_Output.Put_Line('Preço do Curso ' || VNOME || ' -  R$' || VVALOR);
END;   


SELECT *
  FROM TCURSO2
 ORDER BY COD_CURSO;


CREATE OR REPLACE FUNCTION EXISTE_ALUNO (PCOD_ALUNO IN TALUNO2.COD_ALUNO%TYPE) RETURN BOOLEAN
IS
  VALUNO NUMBER (10);
BEGIN
   SELECT COD_ALUNO
     INTO VALUNO
     FROM TALUNO2
    WHERE COD_ALUNO = PCOD_ALUNO; 
   RETURN TRUE;
EXCEPTION
   WHEN OTHERS THEN
     RETURN FALSE;
END;

DECLARE
  VCODIGO INTEGER := &COD_ALUNO;
  VNOME TALUNO2.NOME%TYPE;
BEGIN
   SELECT NOME
     INTO VNOME
     FROM TALUNO2
    WHERE COD_ALUNO = VCODIGO;
  IF EXISTE_ALUNO(VCODIGO) THEN
    Dbms_Output.Put_Line('Aluno ' || VNOME ||' encontrado');
  ELSE
    Dbms_Output.Put_Line('Aluno' || VNOME ||' não encontrado');
  END IF;
END;

CREATE OR REPLACE PROCEDURE CADASTRA_ALUNO (PCOD_ALUNO IN TALUNO2.COD_ALUNO%TYPE, 
                                            PNOME IN TALUNO2.NOME%TYPE,
                                            PCEP IN TALUNO2.CEP%TYPE,
                                            PCIDADE IN TALUNO2.CIDADE%TYPE,
                                            PESTADO IN TALUNO2.ESTADO%TYPE,
                                            PSALARIO IN TALUNO2.SALARIO%TYPE)
IS
BEGIN
   IF(NOT EXISTE_ALUNO(PCOD_ALUNO)) THEN
     INSERT INTO TALUNO2 (COD_ALUNO,  NOME,  CEP,  CIDADE,  ESTADO,  SALARIO)
                  VALUES (PCOD_ALUNO, PNOME, PCEP, PCIDADE, PESTADO, PSALARIO);
     Dbms_Output.Put_Line('Aluno cadastrado com sucesso');
   ELSE
     Dbms_Output.Put_Line('Aluno já cadastrado'); 
   END IF;
END;

BEGIN
  CADASTRA_ALUNO(11, 'Claudia', '13481091', 'Fortaleza', 'CE', 1200);
END;

SELECT * 
  FROM TALUNO2 
  ORDER BY COD_ALUNO;
