--ESPECIFICAÇÃO OU DECLARAÇÃO
CREATE OR REPLACE PACKAGE PKG_ALUNO
IS
  VCIDADE VARCHAR2 (30); --VAR PUBLICA
  VMEDIA NUMBER (8,2); --VAR PUBLICA
  VNOME VARCHAR2 (30); --VAR PUBLICA
  PROCEDURE DELETA_ALUNO (PCOD_ALUNO NUMBER); --PROCEDURE PUBLICA
  PROCEDURE MEDIA_CONTRATOS; --PROCEDURE PUBLICA
  PROCEDURE CON_ALUNO (PCOD_ALUNO NUMBER); --PROCEDURE PUBLICA
END;

--BODY
CREATE OR REPLACE PACKAGE BODY PKG_ALUNO
IS
    VTESTE VARCHAR(20); --VARIAVEL LOCAL PRIVADA
    
    PROCEDURE MEDIA_CONTRATOS
    IS
    BEGIN
      VTESTE := 'TESTE';
      SELECT AVG(TOTAL)
        INTO VMEDIA
        FROM TCONTRATO2;
    END;
    
    --CONSULTA ALUNO
    PROCEDURE CON_ALUNO (PCOD_ALUNO NUMBER)
    IS
    BEGIN
       VNOME := '';
       SELECT NOME
         INTO VNOME
         FROM TALUNO2
         WHERE COD_ALUNO = PCOD_ALUNO;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        Dbms_Output.Put_Line('Aluno não existe');
    END;
    
    PROCEDURE DELETA_ALUNO (PCOD_ALUNO NUMBER)
    IS
    BEGIN
    CON_ALUNO(PCOD_ALUNO);
    IF LENGTH(VNOME) > 0 THEN
        DELETE FROM TALUNO2
          WHERE COD_ALUNO = PCOD_ALUNO;
          COMMIT;
          Dbms_Output.Put_Line('Aluno(a)' || VNOME || ' excluido(a) com sucesso!');
    END IF;
    END;
END;    


--CHAMADA PROCEDURE DELETA ALUNO
EXEC PKG_ALUNO.DELETA_ALUNO(10);

INSERT ALL 
    INTO TALUNO2 VALUES (10,'AAAA','AAAA','1234','QW',1234,'10/02/2001')
    INTO TALUNO2 VALUES (11,'BBBB','AAAA','1234','QW',1234,'10/02/2001')
    SELECT * FROM DUAL;
  

SELECT * FROM TALUNO2 ORDER BY COD_ALUNO DESC;


--CHAMADA PROCEDURE MEDIA CONTRATOS
DECLARE
  M NUMBER;
BEGIN
  PKG_ALUNO.MEDIA_CONTRATOS; --EXECUTA PROCEDURE
  M := PKG_ALUNO.VMEDIA; --VMEDIA VARIAVEL PUBLICA PACKAGE
  Dbms_Output.Put_Line('Média: ' || M);
END;



--CHAMADA PROCEDURE CONSULTA ALUNO
DECLARE
  NOME VARCHAR(30);
BEGIN
  PKG_ALUNO.CON_ALUNO(2);
  NOME := PKG_ALUNO.VNOME;
  Dbms_Output.Put_Line('Nome: ' || NOME);
END;
--SEMELHANTES 
BEGIN
  PKG_ALUNO.CON_ALUNO(2);
  Dbms_Output.Put_Line('Nome: ' || PKG_ALUNO.VNOME);
END;

