
----  UNION ALL - UNION

SELECT COD_ALUNO, TOTAL, DESCONTO
  FROM TCONTRATO2
 WHERE COD_ALUNO = 1
  UNION ALL       ---Nao agrupa iguais
  --UNION         ---Agrupa iguais
SELECT COD_ALUNO, TOTAL, DESCONTO
  FROM TCONTRATO2
 WHERE TOTAL >= 1000;


-- UNION ALL E UNION - 3 SELECT
SELECT COD_CONTRATO, DATA, TOTAL --, 'UNION 1' AS QUERY
FROM   TCONTRATO2
WHERE  TOTAL >= 1000 AND TOTAL < 2000
--RETURN COD_CONTRATO = 3,4

UNION  ALL

SELECT COD_CONTRATO, DATA, TOTAL -- , 'UNION 2' AS QUERY
FROM   TCONTRATO2
WHERE  DESCONTO IS NOT NULL
--RETURN COD_CONTRATO = 1,2,5,6,7

UNION

SELECT COD_CONTRATO, DATA, TOTAL --, 'UNION 3' AS QUERY
FROM   TCONTRATO2
WHERE  TOTAL > 2000
--RETURN COD_CONTRATO = 1

ORDER  BY COD_CONTRATO;

--ORDER  BY QUERY;




--
SELECT COD_CONTRATO, DATA, DESCONTO, TOTAL
FROM   TCONTRATO
WHERE  DESCONTO IS NOT NULL

INTERSECT
--Registros estao presentes em todos os conjuntos.

SELECT COD_CONTRATO, DATA, DESCONTO, TOTAL
FROM   TCONTRATO
WHERE  TOTAL > 1000

ORDER  BY COD_CONTRATO;


--
SELECT COD_CONTRATO, DATA, DESCONTO, TOTAL
FROM   TCONTRATO
WHERE  DESCONTO IS NOT NULL

MINUS  -- traz todos os registros da primeira consulta
       -- menos os da segunda consulta ( ignora repetido )

SELECT COD_CONTRATO, DATA, DESCONTO, TOTAL
FROM   TCONTRATO
WHERE  TOTAL > 2000

ORDER  BY 1;










--
INSERT INTO TALUNO (COD_ALUNO, NOME)
VALUES( (SELECT NVL(MAX(COD_ALUNO),0) + 1 FROM TALUNO),
        'CLEBER');

--
SELECT * FROM TALUNO;


--
SELECT (SELECT MAX(Total) FROM TContrato) MAIOR,
       (SELECT MIN(Total) FROM TContrato) MENOR
FROM DUAL;

--








--Exercicios
--1
SELECT COD_CONTRATO, TOTAL, 'CONTRATOS' STRING
FROM TCONTRATO
 UNION
SELECT COD_CONTRATO, SUM(VALOR) VALOR, 'ITENS' STRING
FROM ITENS
GROUP BY COD_CONTRATO
ORDER BY 3,1;

--2
SELECT COD_CONTRATO, DATA, TOTAL
FROM TCONTRATO
 MINUS
SELECT COD_CONTRATO, DATA, TOTAL
FROM TCONTRATO
WHERE NVL(DESCONTO,0) = 0
 INTERSECT
SELECT CON.COD_CONTRATO, CON.DATA, CON.TOTAL
FROM TALUNO ALU, TCONTRATO CON
WHERE ALU.COD_ALUNO = CON.COD_ALUNO
AND ALU.ESTADO = 'RS';








