--RANK() OVER ORDER BY POR SOMA_TOTAL AGRUPADA POR COD_ALUNO COM POSIÇÕES EMPATADAS
SELECT COD_ALUNO,
       SUM(TOTAL) SOMA_TOTAL,
       RANK() OVER (ORDER BY SUM(TOTAL) DESC) POSICAO
  FROM TCONTRATO2
 GROUP BY (COD_ALUNO);
      
--RANK() OVER ORDER BY POR SOMA_TOTAL AGRUPADO POR COD_ALUNO + DATA COM POSIÇÕES EMPATADAS
SELECT DATA,
       COD_ALUNO,
       SUM(TOTAL) SOMA_TOTAL,
       RANK() OVER (ORDER BY SUM(TOTAL) DESC) POSICAO
  FROM TCONTRATO2
 GROUP BY (DATA,COD_ALUNO);


--RANK() OVER PARTITION BY POSIÇÃO POR GRUPO
SELECT DATA,
       COD_ALUNO,
       SUM(TOTAL),
       RANK () OVER (PARTITION BY DATA ORDER BY SUM(TOTAL) DESC) POSICAO
  FROM TCONTRATO2
 GROUP BY (DATA, COD_ALUNO)
 ORDER BY DATA;
 
--DENSE_RANK() OVER (POSIÇÕES EMPATADAS, PORÉM APÓS AS POSIÇÕES EMPATADAS O NÚMERO SEGUE A SEQUENCIA SER PULAR OS QUE ESTÃO EMPATADOS)
SELECT COD_ALUNO,
       TOTAL,
       RANK() OVER (ORDER BY TOTAL DESC) "RANK()",
       DENSE_RANK() OVER (ORDER BY TOTAL DESC) "DENSE_RANK()"       
  FROM TCONTRATO2
 GROUP BY (COD_ALUNO,TOTAL);       


--RATION TO REPORT (% DE CADA ITEM EM RELAÇÃO AO TOTAL)
SELECT Cod_aluno,
       SUM(TOTAL) "Total do cliente",   
       ROUND (RATIO_TO_REPORT(SUM(TOTAL)) OVER () *100,2)"% do Total"
  FROM TCONTRATO2
 GROUP BY (COD_ALUNO);
 
 --PORCENTAGEM POR GRUPO
 SELECT COD_ALUNO,
       Trunc(DATA),
       SUM(total) "Total do Dia",
       ROUND(RATIO_TO_REPORT(SUM(total)) OVER(PARTITION BY
       Trunc(DATA)) * 100, 2) "% do Dia"
FROM TCONTRATO2
GROUP BY COD_ALUNO, Trunc(DATA)
ORDER BY 2 ASC, COD_ALUNO;


--LAG E LEAD
SELECT DATA, SUM(TOTAL) TOTAL_DIA,
  LAG  (SUM(TOTAL),1) OVER (ORDER BY DATA) ANTERIOR,
  LEAD (SUM(TOTAL),1) OVER (ORDER BY DATA) PROXIMO
FROM TCONTRATO2
GROUP BY DATA
ORDER BY DATA;
 
 