CREATE TABLE EMPLOYEES
(
    EMPLOYEE_ID NUMBER (4),
    NAME VARCHAR2(30),
    PRIMARY KEY (EMPLOYEE_ID)
);

SELECT * FROM EMPLOYEES;

CREATE TABLE SALARIES
(
    EMPLOYEE_ID NUMBER(4),
    SALARY NUMBER (5),
    PRIMARY KEY (EMPLOYEE_ID)
);

SELECT * FROM SALARIES;

INSERT ALL
    INTO EMPLOYEES VALUES (2, 'CREW')
    INTO EMPLOYEES VALUES (4, 'HAVEN')
    INTO EMPLOYEES VALUES (5, 'KRISTIAN')
    SELECT * FROM DUAL;

INSERT ALL
    INTO SALARIES  VALUES (5, 76071)
    INTO SALARIES  VALUES (1, 22517)
    INTO SALARIES  VALUES (4, 22517)
    SELECT * FROM DUAL;
    

SELECT E.EMPLOYEE_ID
  FROM EMPLOYEES E, SALARIES S
  WHERE E.EMPLOYEE_ID NOT IN (SELECT S.EMPLOYEE_ID FROM SALARIES);   
  
SELECT E.EMPLOYEE_ID, S.EMPLOYEE_ID
  FROM EMPLOYEES E, SALARIES S
  WHERE E.EMPLOYEE_ID <> S.EMPLOYEE_ID;

SELECT
     CASE
        WHEN E.EMPLOYEE_ID IS NULL THEN S.EMPLOYEE_ID
        ELSE E.EMPLOYEE_ID
     END AS employee_id
  FROM EMPLOYEES E FULL OUTER JOIN SALARIES S
   ON E.EMPLOYEE_ID = S.EMPLOYEE_ID
   WHERE E.NAME IS NULL
   OR S.SALARY IS NULL
   ORDER BY S.EMPLOYEE_ID ASC;     