SELECT * FROM EMPLOYEE2 ORDER BY ID;

SELECT * FROM DEPARTMENT2;

SELECT DATA,
       COD_ALUNO,
       SUM(TOTAL),
       RANK () OVER (PARTITION BY DATA ORDER BY SUM(TOTAL) DESC) POSICAO
  FROM TCONTRATO2
 GROUP BY (DATA, COD_ALUNO)
 ORDER BY DATA;
 
 
 SELECT * FROM
 (
   SELECT ROWNUM NREG,
     D.NAME DEPARTMENT,
     E.NAME EMPLOYEE,
     E.SALARY,
     RANK () OVER (PARTITION BY D.NAME ORDER BY (SALARY) DESC) ORDEMSAL
    FROM EMPLOYEE2 E,DEPARTMENT2 D
   WHERE D.ID = E.DEPARTMENTID 
   GROUP BY (D.NAME,E.NAME,E.SALARY,ROWNUM)
   ORDER BY NREG
 )
    WHERE NREG > 4;
    

SELECT D.NAME DEPARTMENT,
          E.NAME EMPLOYEE,
          E.SALARY,
          RANK () OVER (PARTITION BY D.NAME ORDER BY (SALARY) DESC) ORDEMSAL
  FROM EMPLOYEE2 E,DEPARTMENT2 D
 WHERE D.ID = E.DEPARTMENTID 
 GROUP BY (D.NAME,E.NAME,E.SALARY,ROWNUM)
 ORDER BY NREG
    
 

 
 
 