SELECT * FROM TEMPLOYEE

CREATE FUNCTION getNthHighestSalary(N IN NUMBER) RETURN NUMBER IS
RESULT NUMBER;
BEGIN
    SELECT ID, SALARY
      FROM TEMPLOYEE
     WHERE SALARY = N; 
    RETURN result;
END;


DECLARE
  VID TEMPLOYEE.ID%TYPE;
  VSAL TEMPLOYEE.SALARY%TYPE;
  N NUMBER(1):= 2;
BEGIN
  SELECT ID, SALARY
    INTO VID, VSAL
    FROM TEMPLOYEE
   WHERE ID = N;
   RETURN 
EXCEPTION
  WHEN NO_DATA_FOUND THEN
      RETURN 0;
END;