CREATE TABLE SCORES
(
    ID NUMBER(3) PRIMARY KEY,
    SCORE NUMBER(5,2)
);



INSERT INTO SCORES VALUES(1,3.50);

INSERT INTO SCORES VALUES(2,3.65);

INSERT INTO SCORES VALUES(3,4.00);

INSERT INTO SCORES VALUES(4,3.85);

INSERT INTO SCORES VALUES(5,4.00);

INSERT INTO SCORES VALUES(6,3.65);


SELECT * FROM SCORES;

SELECT SCORE,
       DENSE_RANK () OVER (ORDER BY SCORE DESC) AS RANK
  FROM SCORES      