SELECT ID FROM (
SELECT ID, 
       RECORDDATE, 
       TEMPERATURE,
       LAG(RECORDDATE) OVER (ORDER BY RECORDDATE) DATA_ANTERIOR,
       LAG(TEMPERATURE) OVER (ORDER BY RECORDDATE) TEMP_ANTERIOR
 FROM WEATHER

) WHERE TEMPERATURE > TEMP_ANTERIOR
  AND TRUNC(RECORDDATE) - TRUNC(DATA_ANTERIOR) = 1;


CREATE TABLE WEATHER(
    ID NUMBER (3),
    RECORDDATE DATE,
    TEMPERATURE NUMBER (3),
    PRIMARY KEY (ID)
);

SELECT * FROM WEATHER

