--CURSOR PARA MULTIPLOS VALORES COM O USO DO FOR EACH
DECLARE
  CURSOR C1 IS
    SELECT * FROM TALUNO2;
  REG TALUNO2%ROWTYPE;
BEGIN
  FOR REG IN C1  --EQUIVALE A: OPEN CURSOR, LAÇO, FETCH, CLOSE CURSOR, EXIT WHEN
  LOOP
    DBMS_OUTPUT.PUT_LINE('Codigo: '||
       LPAD(REG.COD_ALUNO,5,'0')||' - ' || 'Nome: '||REG.NOME);
  END LOOP;
END;

--CURSOR COM PARAMETROS - SEM LAÇO COM APENAS 1 RESULTADO
DECLARE
  CURSOR C1 (PCOD_ALUNO NUMBER) IS
    SELECT * FROM TALUNO2
    WHERE COD_ALUNO = PCOD_ALUNO
   FOR UPDATE OF NOME NOWAIT; --BLOQUEIA A COLUNA NOME PARA ALTERACAO
  
  REG C1%ROWTYPE;
BEGIN
  OPEN C1(&CODIGO);
  FETCH C1 INTO REG;
  DBMS_OUTPUT.PUT_LINE(REG.COD_ALUNO ||' - ' || REG.NOME || ' - ' || REG.CIDADE);
  CLOSE C1; --LIBERA O REGISTRO PARA ALTERACAO
END;