--CREATE SPECIFICATION PACKAGE
CREATE OR REPLACE PACKAGE NOME_PACKAGE
IS
    --DECLARAÇÃO DE VARIAVEIS, CURSORES, PROCEDURES E FUNCTIONS (PÚBLICAS)
END;

--CREATE BODY PACKAGE
CREATE OR REPLACE PACKAGE BODY NOME_PACKAGE
IS
    --DECLAREÇÃO DE VARIAVIES, CURSORES, PROCEDURES E FUNCTIONS (PRIVADAS)
END

--DROP SPECIFICATION
DROP PACKAGE NOME_PACKAGE;

--DROP BODY
DROP PACKAGE BODY NOME_PACKAGE;

--EXEMPLOS DE PACKAGES: C:\Users\Hino\Documents\Treinamento SQL - Oracle\Projetos\Projeto 2 - Material Udemy\Editor\Comandos PL-SQL\CAP22_PACKAGES