--CREATE PROCEDURE
CREATE OR REPLACE PROCEDURE NOME_DA_PROCEDURE (PARAMETERS)
IS
  VARIAVEIS
BEGIN
  COMANDS;
END;

--DROPAR PROCEDURE
DROP PROCEDURE NOME_DA_PROCEDURE;

--EXECUTAR A PROCEDURE
EXECUTE or EXEC NOME_DA_PROCEDURE;

--EXECUTAR A PROCEDURE EM UM BLOCO ANONIMO
DECLARE
  V1 INTEGER := &V1;
BEGIN
  NOME_DA_PROCEDURE(V1); --CHAMA A PROCEDURE PASSANDO O VALOR DE V1 
END;

--TIPOS DE PARAMETROS
--IN: ENTRADA
--OUT: SAIDA
-- IN OUT: ENTRADA E SAIDA

--EXEMPLO DE CREATE PROCEDURE MULTIPLOS PARAMETROS, IN E OUT
CREATE OR REPLACE PROCEDURE CONSULTA_ALUNO
( PCODIGO        IN  TALUNO2.COD_ALUNO%TYPE,
  PNOME          OUT TALUNO2.NOME%TYPE,
  PCEP           OUT TALUNO2.CEP%TYPE,
  PCIDADE        OUT TALUNO2.CIDADE%TYPE)
IS
BEGIN
  SELECT NOME, CEP, CIDADE
  INTO   PNOME, PCEP, PCIDADE
  FROM   TALUNO2
  WHERE  COD_ALUNO = PCODIGO;
END;

--EXECUTAR A PROCEDURE COM MULTIPLOS PARAMETROS
DECLARE
  VNOME VARCHAR2(30);
  VCIDADE VARCHAR(30);
  VCEP VARCHAR(10);
  VCOD INTEGER := &CODIGO;
BEGIN
 --Consulta_aluno(vcod, vnome, vcep, vcidade);

  CONSULTA_ALUNO(PNOME => VNOME,
                 PCODIGO => VCOD,
                 PCIDADE => VCIDADE,
                 PCEP => VCEP);

  DBMS_OUTPUT.PUT_LINE(VNOME);
  DBMS_OUTPUT.PUT_LINE(VCIDADE);
  DBMS_OUTPUT.PUT_LINE(VCEP);
END;


--PROCEDURE + CURSOR + RECORD + PARAMETRO IN OUT
CREATE OR REPLACE PROCEDURE CONSULTA_ALUNO_2 (PREGISTRO IN OUT TALUNO2%ROWTYPE)
IS
  CURSOR CSQL IS
    SELECT *
      FROM TALUNO2;
     WHERE COD_ALUNO = PREGISTRO.COD_ALUNO;
BEGIN
  OPEN CSQL;
  FETCH CSQL INTO PREGISTRO; --ATRIBUI REGISTRO A VARIAVEL PREGISTRO
  END CSQL
END;  

--EXECUTAR A PROCEDURE ACIMA
DECLARE
   REGISTRO TALUNO2%ROWTYPE;
BEGIN
   REGISTRO.COD_ALUNO := 1;
   CONSULTA_ALUNO_2(REGISTRO) --CHAMANDO PROCEDURE PASSANDO UM RECORD COM A TABELA TALUNO2
   DBMS_OUTPUT.PUT_LINE(REGISTRO.NOME);
   DBMS_OUTPUT.PUT_LINE(' - 'REGISTRO.CIDADE || ' - ' || REGISTRO.CEP);
END;