--ELEMENTOS TRIGGER:
--TEMPO: BEFORE(ANTES DO COMANDO SER EXECUTADO), AFTER (DEPOIS DO COMANDO SEM EXECUTADO), INSTEAD OF (SUBSTITUI O EVENTO, APENAS EM VIEWS)
--EVENTOS: INSERT, UPDATE, DELETE
--TIPO: STATEMENT (NIVEL DE COMANDOS, EXECUTADO UMA UNICA VEZ POR COMANDO), FOR EACH ROW (NIVEL DE LINHA, EXECUTADO EM TODO LINHA QUE O MANDO DML AFETA A TABELA)
--CORPO: AÇÕES QUE A TRIGGER EXECUTA


--CREATE TRIGGER STARMENTE
CREATE OR REPLACE TRIGGER NOME_TRIGGER
{BEFORE | AFTER | INSTEAD OF}
EVENTO_TRIGGER1
[OR EVENTO_TRIGGER2
[OR EVENTO_TRIGGER3]]
ON NOME_TABELA
[DECLARE
    VARIAVEIS]
BEGIN
    BLOCO PL/SQL
[EXCEPTION
    TRATAMENTO DE EXCEPTIONS]
END;

--CREATE TRIGGER FOR EACH ROW
CREATE OR REPLACE TRIGGER NOME_TRIGGER
{BEFORE / AFTER / INSTEAD OF}
EVENTO_TRIGGER1
[OR EVENTO_TRIGGER2
[OR EVENTO_TRIGGER3]]
ON NOME_TABELA
[REFERENCING [OLD]
             [NEW]]
FOR EACH ROW
[WHEN CONDIÇÃO_DE_EXECUÇÃO]
[DECLARE
    VARIAVEIS]
BEGIN
    BLOCO PL/SQL
[EXCEPTION
    TRATAMENTO DE EXCEPTIONS]
END;

--ENABLE/DISABLE TRIGGER
ALTER TRIGGER NOME_TRIGGER {ENABLE / DISABLE};

--ENABLE/DISABLE ALL TRIGGER OF TABLE
ALTER TABLE NOME_TABELA {ENABLE / DISABLE} ALL TRIGGERS;

--DROPAR TRIGGER
DROP TRIGGER NOME_TRIGGER;

--EXEMPLOS DE TRIGGERS: C:\Users\Hino\Documents\Treinamento SQL - Oracle\Projetos\Projeto 2 - Material Udemy\Editor\Comandos PL-SQL\CAP23_TRIGGERS