--UNION (AGRUPA O VALOR DOS DOIS SELECTS, AGRUPANDO OS REGISTROS DUPLICADOS)
SELECT * FROM NOME_TABELA
UNION
SELECT * FROM NOME_TABELA2

--UNION ALL (AGRUPA O VALOR DOS DOIS SELECTS, MOSTRANDO TODOS OS DADOS DAS DUAS TABELAS)
SELECT * FROM NOME_TABELA
UNION ALL
SELECT * FROM NOME_TABELA2

--INTERSECT (AGRUPA O VALOR DOS DOIS SELECTS, MOSTRANDO APENAS AS LINHAS DUPLICADAS)
SELECT * FROM NOME_TABELA
INTERSECT
SELECT * FROM NOME_TABELA2

--MINUS (AGRUPA O VALOR DOS DOIS SELECTS, RETIRANDO OS REGISTRO DUPLICADOS. EX: TABLE1{1,2,3} - TABLE2{1} = 2,3)
SELECT * FROM NOME_TABELA
MINUS
SELECT * FROM NOME_TABELA2


--EXEMPLO:
SELECT COD_ALUNO, TOTAL, DESCONTO -- VALORES COD_ALUNO (1,2,3)
  FROM TCONTRATO2
 WHERE TOTAL >= 1000
  --UNION       --(1,2,3) AGRUPA DADOS DUPLICADOS
  --UNION ALL   --(1,3,2,1) MOSTRA TODOS OS DADOS
  --INTERSECT   --(1) MOSTRA APENAS OS DADOS DUPLICADOS 
  --MINUS       -- (2,3) RETIRA DADOS DUPLICADOS
SELECT COD_ALUNO, TOTAL, DESCONTO -- VALORES COD_ALUNO (1)
  FROM TCONTRATO2
 WHERE COD_ALUNO = 1;

 --MAIS EXEMPLOS DE OPERADOS SET: C:\Users\Hino\Documents\Treinamento SQL - Oracle\Projetos\Projeto 2 - Material Udemy\Editor\Comandos PL-SQL\CAP24_OPERADOS_SET

