
--CREATE VIEW
CREATE OR REPLACE VIEW NOME_DA_VIEW
AS
  SELECT NOME_DA_COLUNA
  FROM NOME_DA_TABELA
  WHERE CONDITION;

--CREATE VIEW COM PARAMETROS DE SAIDA (SE COMPORTA COMO UM APELIDO)
CREATE OR REPLACE VIEW NOME_DA_VIEW (APELIDO_DA_COLUNA_1, APELIDO_DA_COLUNA_2)
AS
   SELECT NOME_DA_COLUNA_1, NOME_DA_COLUNA_2
   FROM NOME_DA_TABELA;

--CHAMAR VIEW
SELECT * FROM NOME_DA_VIEW

--MOSTRAR TODAS AS VIEWS
SELECT VIEW_NAME, TEXT
  FROM USER_VIEWS;




