-- Todas as empresas sem repeti��o (todas do select superior e as do inferior que n�o estiverem no superior)
SELECT DISTINCT FSNFENTRADA.CODEMPRESA, GEEMPRESA.RAZAOSOCIAL 
  FROM FSNFENTRADA, GEEMPRESA
 WHERE GEEMPRESA.CODEMPRESA = FSNFENTRADA.CODEMPRESA
 UNION 
SELECT FSNFSAIDA.CODEMPRESA, GEEMPRESA.RAZAOSOCIAL 
  FROM FSNFSAIDA, GEEMPRESA
 WHERE GEEMPRESA.CODEMPRESA = FSNFSAIDA.CODEMPRESA
 GROUP BY FSNFSAIDA.CODEMPRESA, GEEMPRESA.RAZAOSOCIAL 
 
-- Todas as empresas com repeti��o (todas do select superior e todas do inferior )
SELECT DISTINCT FSNFENTRADA.CODEMPRESA, GEEMPRESA.RAZAOSOCIAL 
  FROM FSNFENTRADA, GEEMPRESA
 WHERE GEEMPRESA.CODEMPRESA = FSNFENTRADA.CODEMPRESA
 UNION ALL
SELECT FSNFSAIDA.CODEMPRESA, GEEMPRESA.RAZAOSOCIAL 
  FROM FSNFSAIDA, GEEMPRESA
 WHERE GEEMPRESA.CODEMPRESA = FSNFSAIDA.CODEMPRESA
 GROUP BY FSNFSAIDA.CODEMPRESA, GEEMPRESA.RAZAOSOCIAL 
 
SELECT DISTINCT FSNFENTRADA.CODEMPRESA, GEEMPRESA.RAZAOSOCIAL 
  FROM FSNFENTRADA, GEEMPRESA
 WHERE GEEMPRESA.CODEMPRESA = FSNFENTRADA.CODEMPRESA
 MINUS
SELECT FSNFSAIDA.CODEMPRESA, GEEMPRESA.RAZAOSOCIAL 
  FROM FSNFSAIDA, GEEMPRESA
 WHERE GEEMPRESA.CODEMPRESA = FSNFSAIDA.CODEMPRESA
 GROUP BY FSNFSAIDA.CODEMPRESA, GEEMPRESA.RAZAOSOCIAL
 
 -- GXN
 SELECT ZANFECABEC.IDCABEC, ZANFECABEC.CHAVENFE, ZANFECABEC.IDXML, ZANFEXML.XML,
       ZANFECABEC.CNPJEMISSAO, EMP_EMIT.NOME NOME_EMISSAO, ZANFECABEC.CNPJDESTINO, EMP_DEST.NOME NOME_DESTINO, 
       ZANFECABEC.CNPJTRANSP, EMP_TRANS.NOME NOME_TRANSP
  FROM ZANFECABEC, ZANFEXML, ZVERPEMP EMP_EMIT, ZVERPEMP EMP_DEST, 
       ZVERPEMP EMP_TRANS
 WHERE ZANFEXML.IDXML (+)= ZANFECABEC.IDXML
   AND EMP_EMIT.CNPJ (+)= ZANFECABEC.CNPJEMISSAO
   AND EMP_DEST.CNPJ (+)= ZANFECABEC.CNPJDESTINO
   AND EMP_TRANS.CNPJ (+)= ZANFECABEC.CNPJTRANSP
   
SELECT ZANFECABEC.IDCABEC, ZANFECABEC.CHAVENFE, ZANFECABEC.CNPJEMISSAO,
       (SELECT ZVERPEMP.NOME
          FROM ZVERPEMP
         WHERE ZVERPEMP.CNPJ = ZANFECABEC.CNPJEMISSAO) NOME_EMISSAO
  FROM ZANFECABEC

SELECT BASE.CNPJEMISSAO, ZVERPEMP.NOME
  FROM (SELECT DISTINCT ZANFECABEC.CNPJEMISSAO
          FROM ZANFECABEC) BASE,
        ZVERPEMP
  WHERE ZVERPEMP.CNPJ = BASE.CNPJEMISSAO
  
SELECT *
  FROM ZACTECABEC, ZACTEXML
 WHERE ZACTEXML.IDXMLCTE = ZACTECABEC.IDXMLCTE
 
SELECT GEMUNICIPIO.CODMUNICIPIO, GEMUNICIPIO.NOME || ' / ' || GEESTADO.SIGLA
  FROM GEMUNICIPIO, GEESTADO
 WHERE GEESTADO.CODESTADO = GEMUNICIPIO.CODESTADO
 
CREATE TABLE BKP_MUNICIPIO AS 
SELECT CODMUNICIPIO, NOME, CODGIASP
  FROM GEMUNICIPIO
   
SELECT *
  FROM BKP_MUNICIPIO
  

CREATE TABLE ESTRUTURA
( 
  PAI   NUMBER,
  FILHO NUMBER
);  

INSERT INTO ESTRUTURA (PAI,FILHO) VALUES (1, 2);  
INSERT INTO ESTRUTURA (PAI,FILHO) VALUES (2, 3);
INSERT INTO ESTRUTURA (PAI,FILHO) VALUES (3, 4);
INSERT INTO ESTRUTURA (PAI,FILHO) VALUES (4, 5.1);
INSERT INTO ESTRUTURA (PAI,FILHO) VALUES (4, 5.2);
INSERT INTO ESTRUTURA (PAI,FILHO) VALUES (1, 2.1);

SELECT *
  FROM ESTRUTURA
  
SELECT PAI, FILHO, LEVEL,
       DECODE(LEVEL, 1, '', LPAD(' ', (LEVEL - 1) * 3, ' ')) || PAI 
  FROM ESTRUTURA
CONNECT BY PAI = PRIOR FILHO
 START WITH PAI = 1
 
DROP TABLE TAB_TESTE;

CREATE TABLE TAB_TESTE
(
  CODIGO    NUMBER(2) NOT NULL,
  SUBGRUPO  NUMBER(2),
  DESCRICAO VARCHAR2(50),
  VALOR     NUMBER,
  CONSTRAINT PK_TAB_TESTE PRIMARY KEY (CODIGO)
);

INSERT INTO TAB_TESTE (CODIGO, SUBGRUPO, DESCRICAO, VALOR) VALUES (1, 1, 'VALOR 1', 10);     
INSERT INTO TAB_TESTE (CODIGO, SUBGRUPO, DESCRICAO, VALOR) VALUES (2, 1, 'VALOR 2', 20);
INSERT INTO TAB_TESTE (CODIGO, SUBGRUPO, DESCRICAO, VALOR) VALUES (3, 1, 'VALOR 3', 30);
INSERT INTO TAB_TESTE (CODIGO, SUBGRUPO, DESCRICAO, VALOR) VALUES (4, 2, 'VALOR 4', 40);
INSERT INTO TAB_TESTE (CODIGO, SUBGRUPO, DESCRICAO, VALOR) VALUES (5, 2, 'VALOR 5', 50);
COMMIT;

SELECT CODIGO, SUBGRUPO, DESCRICAO, VALOR,
       SUM(VALOR) OVER (PARTITION BY SUBGRUPO ORDER BY CODIGO) VALOR_ACUMULADO_SUBGRUPO,
       SUM(VALOR) OVER (ORDER BY CODIGO) VALOR_ACUMULADO_GERAL,
       LEAD(VALOR) OVER (ORDER BY CODIGO) PROXIMO_VALOR,
       LAG(VALOR) OVER (ORDER BY CODIGO) VALOR_ANTERIOR
  FROM TAB_TESTE  
 ORDER BY SUBGRUPO, CODIGO  
 
 SELECT COUNT(*) TOTAL_NOTAS,
        SUM(FSNFSAIDA.VLRTOTALNOTA) SOMA_VALOR_TOTAL,
        MAX(FSNFSAIDA.VLRTOTALNOTA) NOTA_COM_MAIOR_VALOR,
        MIN(FSNFSAIDA.VLRTOTALNOTA) NOTA_COM_MENOR_VALOR,
        AVG(FSNFSAIDA.VLRTOTALNOTA) VALOR_MEDIO_POR_NOTA,
        ROUND(AVG(FSNFSAIDA.VLRTOTALNOTA), 2) VALOR_MEDIO_ARREDONDADO,
        CEIL(AVG(FSNFSAIDA.VLRTOTALNOTA)) ARREDONDAMENTO_PRA_CIMA,
        FLOOR(AVG(FSNFSAIDA.VLRTOTALNOTA)) ARREDONDAMENTO_PRA_BAIXO,
        TRUNC(AVG(FSNFSAIDA.VLRTOTALNOTA)) CORTA_DECIMAIS_SEM_ARREDONDAR
   FROM FSNFSAIDA
  WHERE FSNFSAIDA.DTEMISSAO BETWEEN TO_DATE('01/01/2022', 'DD/MM/YYYY')
                                AND TO_DATE('31/01/2022 23:59', 'DD/MM/YYYY HH24:MI')
                                
SELECT FSNFITEM.CODPRODUTO, 
       FSPRODUTO.DESCRICAO,
       SUM(FSNFITEM.VALORTOTAL) VALOR_TOTAL
  FROM FSNFSAIDA,
       FSNFITEM,
       FSPRODUTO
 WHERE FSNFSAIDA.DTEMISSAO BETWEEN TO_DATE('01/01/2022', 'DD/MM/YYYY')
                               AND TO_DATE('31/01/2022 23:59', 'DD/MM/YYYY HH24:MI')
   AND FSNFITEM.CODESTAB = FSNFSAIDA.CODESTAB
   AND FSNFITEM.INDICENFSAI = FSNFSAIDA.INDICENFSAI
   AND FSPRODUTO.CODPRODUTO = FSNFITEM.CODPRODUTO
 GROUP BY FSNFITEM.CODPRODUTO,
          FSPRODUTO.DESCRICAO
 ORDER BY VALOR_TOTAL DESC, CODPRODUTO ASC
 
 
SELECT CODEMPRESA, 
       RAZAOSOCIAL,
       LPAD(RAZAOSOCIAL, 100, '.'),
       RPAD(RAZAOSOCIAL, 100, '.'),
       SUBSTR(RAZAOSOCIAL, 1, 20),
       INSTR(RAZAOSOCIAL, 'A'),
       UPPER('teste'),
       LOWER(RAZAOSOCIAL),
       INITCAP('epis horizont equipamentos de seguranca ltda'),
       TRIM(RAZAOSOCIAL || '  ') -- REMOVE ESPA�OES
  FROM GEEMPRESA