-- Estabelecimentos
SELECT *
  FROM GEESTAB -- ESTADO
  
-- Endereços
SELECT *
  FROM GEENDERECO -- ENDEREÇO
  
-- Estabelecimento x Endereço
SELECT *
  FROM GEESTAB,
       GEENDERECO
 WHERE GEENDERECO.CODENDERECO = GEESTAB.CODENDERECO
 
 -- Localidades
SELECT * 
  FROM GEPAIS -- PAIS
  
SELECT *
  FROM GEESTADO -- ESTADO
  
SELECT *
  FROM GEMUNICIPIO -- MUNICIPIO
  

SELECT *
  FROM GEMUNICIPIO,
       GEESTADO,
       GEPAIS
 WHERE GEESTADO.CODESTADO = GEMUNICIPIO.CODESTADO
   AND GEPAIS.CODPAIS = GEESTADO.CODPAIS
   
 SELECT *
   FROM GEMUNICIPIOIBGE -- MUNICÍPIO PADRÃO IBGE
   
 SELECT *
   FROM GEESTADOIBGE -- ESTADO PADRÃO DO IBGE
   
 SELECT *
   FROM GEPAISBACEN -- PAIS PADRÃO DO BANCO CENTRAL
   
 -- Moedas
 SELECT *
   FROM GEMOEDA -- MOEDAS
   
 SELECT *
   FROM GECAMBIO -- COTAÇÕES/CAMBIO
       
 -- Forma e condição de pagto
 SELECT *
   FROM VEFORMAPGTO -- FORMA DE PAGAMENTO
 
SELECT *
  FROM VECONDPGTO -- CONDIÇÃO DE PAGAMENTO
  
SELECT *
  FROM VEDETCONDPGTO -- DETALHE DA CONDIÇÃO DE PAGAMENTO (PARCELAS E PERCENTUAL)
  
-- Empresas
SELECT *
  FROM GEEMPRESA -- EMPRESAS
  
SELECT *
  FROM GEEMPRESAPARAMESTAB -- DADOS DA EMPRESA POR ESTABELECIMENTO
  
 SELECT *
   FROM GEENDEMPRESA -- ENDEREÇOS DAS EMPRESAS 
  
 SELECT *
   FROM PEEMPRESA -- PERSONALIZADA DE EMPRESAS