
--SELECT com inner join
SELECT NC1.NOME_DA_COLUNA, NC2.NOME_DA_COLUNA
  FROM NOME_DA_TABELA_1 AS NC1, NOME_DA_TABELA_2 AS NC2
 WHERE NC1.NOME_DA_COLUNA = NC2.NOME_DA_COLUNA;

--SELECT com Left join
SELECT NC1.NOME_DA_COLUNA, NC2.NOME_DA_COLUNA
  FROM NOME_DA_TABELA_1 AS NC1, NOME_DA_TABELA_2 AS NC2
 WHERE NC1.NOME_DA_COLUNA (+) = NC2.NOME_DA_COLUNA;

 --SELECT com Right join
SELECT NC1.NOME_DA_COLUNA, NC2.NOME_DA_COLUNA
  FROM NOME_DA_TABELA_1 AS NC1, NOME_DA_TABELA_2 AS NC2
 WHERE NC1.NOME_DA_COLUNA = NC2.NOME_DA_COLUNA (+);
