DROP TABLE TAB_TESTE;

CREATE TABLE TAB_TESTE
(
  CODIGO    NUMBER(2) NOT NULL,
  SUBGRUPO  NUMBER(2),
  DESCRICAO VARCHAR2(50),
  VALOR     NUMBER,
  CONSTRAINT PK_TAB_TESTE PRIMARY KEY (CODIGO)
);

INSERT INTO TAB_TESTE (CODIGO, SUBGRUPO, DESCRICAO, VALOR) VALUES (1, 1, 'VALOR 1', 10);     
INSERT INTO TAB_TESTE (CODIGO, SUBGRUPO, DESCRICAO, VALOR) VALUES (2, 1, 'VALOR 2', 20);
INSERT INTO TAB_TESTE (CODIGO, SUBGRUPO, DESCRICAO, VALOR) VALUES (3, 1, 'VALOR 3', 30);
INSERT INTO TAB_TESTE (CODIGO, SUBGRUPO, DESCRICAO, VALOR) VALUES (4, 2, 'VALOR 4', 40);
INSERT INTO TAB_TESTE (CODIGO, SUBGRUPO, DESCRICAO, VALOR) VALUES (5, 2, 'VALOR 5', 50);
COMMIT;

SELECT CODIGO, SUBGRUPO, DESCRICAO, VALOR,
       SUM(VALOR) OVER (PARTITION BY SUBGRUPO ORDER BY CODIGO) VALOR_ACUMULADO_SUBGRUPO,
       SUM(VALOR) OVER (ORDER BY CODIGO) VALOR_ACUMULADO_GERAL,
       LEAD(VALOR) OVER (ORDER BY CODIGO) PROXIMO_VALOR,
       LAG(VALOR) OVER (ORDER BY CODIGO) VALOR_ANTERIOR
  FROM TAB_TESTE 
 ORDER BY SUBGRUPO,CODIGO